<a href="https://colab.research.google.com/github/Sarthakpal23/fitness-tracker-/blob/main/fitness_analysis_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [164]:
!pip install streamlit
!pip install pyngrok

Requirement already satisfied: streamlit in /usr/local/lib/python3.12/dist-packages (1.55.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.3.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.46)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.0)
Requirement already satisfied: pandas<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.9.1)
Requirement already satisfied: protobuf<7,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.5.1)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.18.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.2.25)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Requirement already satisfied: pyngrok in /usr/local/lib/python3.12/dist-packages (7.5.1)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.12/dist-packages (from pyngrok) (6.0.3)

In [165]:
!pip install streamlit

Requirement already satisfied: streamlit in /usr/local/lib/python3.12/dist-packages (1.55.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.3.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.46)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.0)
Requirement already satisfied: pandas<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.9.1)
Requirement already satisfied: protobuf<7,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.5.1)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.18.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.2.25)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)

In [166]:
%%writefile app.py
# ============================================================
# ULTIMATE FITNESS AI DASHBOARD
# Developed by: Sarthak Pal
# Instagram Style UI + ML + AI Diet Planner
# ============================================================

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# ------------------------------------------------------------
# PAGE CONFIG (ONLY ONCE)
# ------------------------------------------------------------
st.set_page_config(page_title="Fitness AI", page_icon="🔥", layout="wide")

# ------------------------------------------------------------
# INSTAGRAM STYLE UI
# ------------------------------------------------------------
st.markdown("""
<style>
html, body, [class*="css"] {
    background-color:#0f0f0f;
    color:white;
    font-family: 'Segoe UI', sans-serif;
}

.main-title {
    font-size:48px;
    font-weight:800;
    background: linear-gradient(90deg,#ff512f,#dd2476);
    -webkit-background-clip:text;
    -webkit-text-fill-color:transparent;
}

.metric-box {
    background: linear-gradient(135deg,#1f1c2c,#928dab);
    padding:20px;
    border-radius:15px;
    text-align:center;
    font-size:20px;
}

section[data-testid="stSidebar"] {
    background: linear-gradient(180deg,#141E30,#243B55);
}

.stButton>button {
    background: linear-gradient(90deg,#ff512f,#dd2476);
    border:none;
    border-radius:20px;
    color:white;
}
</style>
""", unsafe_allow_html=True)

st.markdown('<p class="main-title">🔥 Fitness AI Dashboard</p>', unsafe_allow_html=True)

# ------------------------------------------------------------
# DATASET
# ------------------------------------------------------------
@st.cache_data
def load_data():
    np.random.seed(42)
    data = pd.DataFrame({
        "Steps": np.random.randint(2000,15000,500),
        "Calories": np.random.randint(1500,3500,500),
        "Heart_Rate": np.random.randint(60,140,500),
        "Sleep": np.random.uniform(4,9,500),
        "BMI": np.random.uniform(18,32,500)
    })

    conditions = [
        (data["Steps"] < 4000),
        (data["Steps"] < 8000),
        (data["Steps"] < 12000),
        (data["Steps"] >= 12000)
    ]

    labels = ["Underactive","Moderate","Healthy","Highly Active"]
    data["Fitness_Level"] = np.select(conditions,labels)

    return data

df = load_data()

# ------------------------------------------------------------
# SIDEBAR
# ------------------------------------------------------------
st.sidebar.title("Navigation")

menu = st.sidebar.radio(
    "Select Page",
    ["Dashboard","Analytics","Prediction AI","AI Diet Planner","Health Report"]
)

# ------------------------------------------------------------
# FITNESS SCORE
# ------------------------------------------------------------
def fitness_score(steps, sleep, bmi):
    score = 0
    if steps > 10000:
        score += 40
    elif steps > 7000:
        score += 30
    else:
        score += 15

    if sleep >= 7:
        score += 30
    else:
        score += 15

    if 18.5 <= bmi <= 24.9:
        score += 30
    else:
        score += 15

    return score

# ------------------------------------------------------------
# DASHBOARD
# ------------------------------------------------------------
if menu == "Dashboard":

    col1,col2,col3,col4 = st.columns(4)

    col1.markdown(f'<div class="metric-box">Records<br>{len(df)}</div>', unsafe_allow_html=True)
    col2.markdown(f'<div class="metric-box">Avg Steps<br>{int(df["Steps"].mean())}</div>', unsafe_allow_html=True)
    col3.markdown(f'<div class="metric-box">Calories<br>{int(df["Calories"].mean())}</div>', unsafe_allow_html=True)
    col4.markdown(f'<div class="metric-box">Sleep<br>{round(df["Sleep"].mean(),2)}</div>', unsafe_allow_html=True)

    st.markdown("### Activity Distribution")

    fig, ax = plt.subplots()
    df["Fitness_Level"].value_counts().plot(kind="bar", ax=ax)
    st.pyplot(fig)

# ------------------------------------------------------------
# ANALYTICS
# ------------------------------------------------------------
elif menu == "Analytics":

    st.subheader("Dataset")
    st.dataframe(df)

    st.subheader("Correlation")

    corr = df.corr(numeric_only=True)
    fig, ax = plt.subplots()
    cax = ax.matshow(corr)
    plt.xticks(range(len(corr.columns)), corr.columns, rotation=90)
    plt.yticks(range(len(corr.columns)), corr.columns)
    st.pyplot(fig)

# ------------------------------------------------------------
# PREDICTION AI
# ------------------------------------------------------------
elif menu == "Prediction AI":

    col1,col2 = st.columns(2)

    with col1:
        steps = st.slider("Steps",1000,20000,7000)
        calories = st.slider("Calories",1000,4000,2200)
        heart = st.slider("Heart Rate",50,160,80)

    with col2:
        sleep = st.slider("Sleep",3.0,10.0,7.0)
        bmi = st.slider("BMI",15.0,35.0,23.0)

    if st.button("Analyze Fitness"):

        X = df.drop("Fitness_Level", axis=1)
        y = df["Fitness_Level"]

        X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

        model = RandomForestClassifier()
        model.fit(X_train,y_train)

        user = pd.DataFrame({
            "Steps":[steps],
            "Calories":[calories],
            "Heart_Rate":[heart],
            "Sleep":[sleep],
            "BMI":[bmi]
        })

        pred = model.predict(user)

        score = fitness_score(steps,sleep,bmi)

        st.success(f"Fitness Level: {pred[0]}")
        st.info(f"Fitness Score: {score}/100")

# ------------------------------------------------------------
# AI DIET PLANNER (COMBINED)
# ------------------------------------------------------------
elif menu == "AI Diet Planner":

    st.subheader("🥗 AI Diet + Smart Meal Generator")

    col1,col2,col3 = st.columns(3)

    with col1:
        bmi = st.slider("BMI",15.0,35.0,23.0)
        steps = st.slider("Daily Steps",1000,20000,8000)

    with col2:
        workout = st.slider("Workout Minutes",0,120,30)
        goal = st.selectbox("Goal",["Fat Loss","Muscle Gain","Maintain"])

    with col3:
        diet_type = st.selectbox("Diet Type",["Balanced","High Protein","Vegetarian","Low Carb"])

    if st.button("Generate Diet Plan"):

        calories = 1800
        calories += int(steps/2000)*50
        calories += int(workout/30)*100

        if goal == "Fat Loss":
            calories -= 300
        elif goal == "Muscle Gain":
            calories += 300

        st.success(f"Daily Calories Target: {calories}")

        breakfast = ["Oats","Eggs","Fruit"]
        lunch = ["Brown Rice","Chicken / Paneer","Vegetables"]
        snack = ["Protein Shake","Nuts"]
        dinner = ["Soup","Salad","Tofu / Fish"]

        if diet_type == "Vegetarian":
            lunch = ["Paneer","Quinoa","Vegetables"]
            dinner = ["Tofu","Salad"]

        if diet_type == "High Protein":
            breakfast = ["Egg Omelette","Protein Shake"]
            snack = ["Greek Yogurt","Almonds"]

        if diet_type == "Low Carb":
            lunch = ["Grilled Chicken","Broccoli"]
            dinner = ["Fish","Vegetables"]

        col4,col5 = st.columns(2)

        with col4:
            st.markdown("### Breakfast")
            for f in breakfast:
                st.write("•",f)

            st.markdown("### Lunch")
            for f in lunch:
                st.write("•",f)

        with col5:
            st.markdown("### Snack")
            for f in snack:
                st.write("•",f)

            st.markdown("### Dinner")
            for f in dinner:
                st.write("•",f)

# ------------------------------------------------------------
# HEALTH REPORT
# ------------------------------------------------------------
elif menu == "Health Report":

    st.subheader("Health Insights")

    st.write("Average Steps:", int(df["Steps"].mean()))
    st.write("Average Calories:", int(df["Calories"].mean()))
    st.write("Average Heart Rate:", int(df["Heart_Rate"].mean()))
    st.write("Average Sleep:", round(df["Sleep"].mean(),2))

# Footer
st.markdown("---")
st.write("Developed by Sarthak Pal | AI Project")

Overwriting app.py

In [192]:
%%writefile app.py
# ============================================================
# ULTIMATE FITNESS AI DASHBOARD
# Advanced UI + Machine Learning + Analytics
# Developed by: Sarthak Pal
# ============================================================

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# ------------------------------------------------------------
# Page Setup
# ------------------------------------------------------------
st.set_page_config(
    page_title="Fitness AI Dashboard",
    page_icon="🏃",
    layout="wide"
)

# ------------------------------------------------------------
# MODERN INSTAGRAM-STYLE UI
# ------------------------------------------------------------
st.set_page_config(
    page_title="Fitness AI",
    page_icon="🔥",
    layout="wide"
)

st.markdown("""
<style>

html, body, [class*="css"]  {
    font-family: 'Segoe UI', sans-serif;
    background-color: #0f0f0f;
    color: white;
}

/* Main Title */
.main-title {
    font-size:48px;
    font-weight:800;
    background: linear-gradient(90deg,#ff512f,#dd2476);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
}

/* Cards */
.card {
    background: rgba(255,255,255,0.05);
    padding: 25px;
    border-radius: 20px;
    backdrop-filter: blur(12px);
    border: 1px solid rgba(255,255,255,0.1);
    transition: 0.3s;
}

.card:hover {
    transform: translateY(-5px);
    box-shadow: 0px 10px 25px rgba(255,0,150,0.2);
}

/* Metrics */
.metric-box {
    background: linear-gradient(135deg,#1f1c2c,#928dab);
    padding: 20px;
    border-radius: 18px;
    text-align:center;
    font-size:20px;
    font-weight:600;
}

/* Sidebar */
section[data-testid="stSidebar"] {
    background: linear-gradient(180deg,#141E30,#243B55);
}

/* Buttons */
.stButton>button {
    background: linear-gradient(90deg,#ff512f,#dd2476);
    border: none;
    border-radius: 20px;
    padding: 10px 25px;
    color: white;
    font-weight: 600;
}

</style>
""", unsafe_allow_html=True)

st.markdown('<p class="main-title">🔥 Fitness AI Social Dashboard</p>', unsafe_allow_html=True)
st.write("AI Powered Health Insights • Smart Analytics • Personalized Fitness")


# ------------------------------------------------------------
# Dataset Generator
# ------------------------------------------------------------
@st.cache_data
def load_data():
    np.random.seed(42)

    data = pd.DataFrame({
        "Steps": np.random.randint(2000, 15000, 500),
        "Calories": np.random.randint(1500, 3500, 500),
        "Heart_Rate": np.random.randint(60, 140, 500),
        "Sleep": np.random.uniform(4, 9, 500),
        "BMI": np.random.uniform(18, 32, 500)
    })

    conditions = [
        (data["Steps"] < 4000),
        (data["Steps"] < 8000),
        (data["Steps"] < 12000),
        (data["Steps"] >= 12000)
    ]

    labels = ["Underactive", "Moderate", "Healthy", "Highly Active"]

    data["Fitness_Level"] = np.select(conditions, labels, default='Unknown')

    return data

df = load_data()

# ------------------------------------------------------------
# Sidebar Navigation
# ------------------------------------------------------------
st.sidebar.title("Navigation")

menu = st.sidebar.radio(
    "Select Page",
    [
        "Dashboard",
        "Analytics",
        "Prediction AI",
        "Diet Plan",
        "Advanced Diet AI", # Added Advanced Diet AI to the menu
        "Health Report"
    ]
)


# ------------------------------------------------------------
# Fitness Score Function
# ------------------------------------------------------------
def fitness_score(steps, sleep, bmi):
    score = 0

    if steps > 10000:
        score += 40
    elif steps > 7000:
        score += 30
    else:
        score += 15

    if sleep >= 7:
        score += 30
    else:
        score += 15

    if 18.5 <= bmi <= 24.9:
        score += 30
    else:
        score += 15

    return score

# ============================================================
# ADVANCED FITNESS INTELLIGENCE MODULE (FitnessAI class)
# ============================================================

class FitnessAI:

    def __init__(self):
        pass

    # --------------------------------------------------------
    # BMR Calculator
    # --------------------------------------------------------
    def calculate_bmr(self, weight, height, age, gender):

        if gender == "Male":
            bmr = 10 * weight + 6.25 * height - 5 * age + 5
        else:
            bmr = 10 * weight + 6.25 * height - 5 * age - 161

        return int(bmr)

    # --------------------------------------------------------
    # Daily Calories
    # --------------------------------------------------------
    def daily_calories(self, bmr, activity_level):

        activity_multiplier = {
            "Low": 1.2,
            "Moderate": 1.5,
            "High": 1.75
        }

        return int(bmr * activity_multiplier[activity_level])

    # --------------------------------------------------------
    # Macro Calculation
    # --------------------------------------------------------
    def macros(self, calories, goal):

        if goal == "Fat Loss":
            protein = calories * 0.40 / 4
            carbs = calories * 0.30 / 4
            fats = calories * 0.30 / 9

        elif goal == "Muscle Gain":
            protein = calories * 0.35 / 4
            carbs = calories * 0.45 / 4
            fats = calories * 0.20 / 9

        else:
            protein = calories * 0.30 / 4
            carbs = calories * 0.40 / 4
            fats = calories * 0.30 / 9

        return {
            "Protein (g)": int(protein),
            "Carbs (g)": int(carbs),
            "Fats (g)": int(fats)
        }

    # --------------------------------------------------------
    # Weekly Diet Plan
    # --------------------------------------------------------
    def weekly_diet(self):

        plan = {
            "Monday": "High Protein Meals",
            "Tuesday": "Balanced Diet",
            "Wednesday": "Low Carb Focus",
            "Thursday": "Muscle Recovery Meals",
            "Friday": "Protein Rich Diet",
            "Saturday": "Athlete Level Nutrition",
            "Sunday": "Light Detox Diet"
        }

        return plan

    # --------------------------------------------------------
    # AI Coach Advice
    # --------------------------------------------------------
    def ai_coach(self, fitness_level, sleep, steps):

        if fitness_level == "Underactive":
            return "Start walking daily and build consistency."

        if sleep < 6:
            return "Improve sleep for better recovery."

        if steps > 12000:
            return "Great work! Focus on recovery and hydration."

        return "Maintain balanced lifestyle."

# ------------------------------------------------------------
# DASHBOARD PAGE
# ------------------------------------------------------------
if menu == "Dashboard":

    st.subheader("Your Fitness Feed")

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.markdown('<div class="metric-box">📊 Records<br><br>'+str(len(df))+'</div>', unsafe_allow_html=True)

    with col2:
        st.markdown('<div class="metric-box">👣 Avg Steps<br><br>'+str(int(df["Steps"].mean()))+'</div>', unsafe_allow_html=True)

    with col3:
        st.markdown('<div class="metric-box">🔥 Calories<br><br>'+str(int(df["Calories"].mean()))+'</div>', unsafe_allow_html=True)

    with col4:
        st.markdown('<div class="metric-box">😴 Sleep<br><br>'+str(round(df["Sleep"].mean(),2))+'</div>', unsafe_allow_html=True)

    st.write("")

    st.markdown("### Activity Trends")

    fig, ax = plt.subplots()
    df["Fitness_Level"].value_counts().plot(kind="bar", ax=ax)
    st.pyplot(fig)


# ------------------------------------------------------------
# ANALYTICS PAGE
# ------------------------------------------------------------
elif menu == "Analytics":

    st.subheader("Dataset Overview")

    st.dataframe(df)

    st.subheader("Correlation Heatmap")

    corr = df.corr(numeric_only=True)

    fig, ax = plt.subplots()
    cax = ax.matshow(corr)
    plt.xticks(range(len(corr.columns)), corr.columns, rotation=90)
    plt.yticks(range(len(corr.columns)), corr.columns)
    st.pyplot(fig)

    st.subheader("Steps vs Calories")

    fig, ax = plt.subplots()
    ax.scatter(df["Steps"], df["Calories"])
    ax.set_xlabel("Steps")
    ax.set_ylabel("Calories")
    st.pyplot(fig)

# ------------------------------------------------------------
# AI PREDICTION PAGE
# ------------------------------------------------------------
elif menu == "Prediction AI":

    st.subheader("Check Your Fitness Status")

    col1, col2 = st.columns(2)

    with col1:
        steps = st.slider("Steps", 1000, 20000, 7000)
        calories = st.slider("Calories Burned", 1000, 4000, 2200)
        heart = st.slider("Heart Rate", 50, 160, 80)

    with col2:
        sleep = st.slider("Sleep Hours", 3.0, 10.0, 7.0)
        bmi = st.slider("BMI", 15.0, 35.0, 23.0)

    if st.button("Analyze My Fitness"):
        X = df.drop("Fitness_Level", axis=1)
        y = df["Fitness_Level"]

        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.2, random_state=42
        )

        model = RandomForestClassifier(n_estimators=200)
        model.fit(X_train, y_train)

        user = pd.DataFrame({
            "Steps": [steps],
            "Calories": [calories],
            "Heart_Rate": [heart],
            "Sleep": [sleep],
            "BMI": [bmi]
        })

        prediction = model.predict(user)

        score = fitness_score(steps, sleep, bmi)

        st.success(f"🏆 Fitness Level: {prediction[0]}")
        st.info(f"⭐ Fitness Score: {score}/100")


# ------------------------------------------------------------
# AI DIET + DIET PLAN PAGE
# ------------------------------------------------------------
elif menu == "Diet Plan":

    st.subheader("🥗 AI Diet Planner")

    st.write("Generate a personalized diet plan using AI")

    # User Inputs
    col1, col2, col3 = st.columns(3)

    with col1:
        bmi = st.slider("BMI", 15.0, 35.0, 23.0)
        age = st.slider("Age", 15, 60, 22)

    with col2:
        steps = st.slider("Daily Steps", 1000, 20000, 8000)
        workout = st.slider("Workout (minutes)", 0, 120, 30)

    with col3:
        goal = st.selectbox(
            "Fitness Goal",
            ["Fat Loss", "Muscle Gain", "Maintain Fitness"]
        )

        diet_type = st.selectbox(
            "Diet Preference",
            ["Balanced", "High Protein", "Vegetarian", "Low Carb"]
        )

    generate = st.button("Generate AI Diet Plan")

    if generate:

        # --------------------------
        # Calorie Calculation
        # --------------------------
        calories = 1800
        calories += int(steps / 2000) * 50
        calories += int(workout / 30) * 100

        if goal == "Fat Loss":
            calories -= 300
        elif goal == "Muscle Gain":
            calories += 350

        # BMI Adjustment
        if bmi > 27:
            goal_result = "Fat Loss"
        elif bmi < 19:
            goal_result = "Weight Gain"
        else:
            goal_result = "Maintain Fitness"

        st.success(f"🎯 Goal: {goal_result}")
        st.info(f"🔥 Recommended Calories: {calories}")

        # --------------------------
        # Base Diet Plan
        # --------------------------
        breakfast = ["Oats", "Eggs", "Green Tea"]
        lunch = ["Brown Rice", "Chicken / Paneer", "Vegetables"]
        snack = ["Protein Shake", "Nuts"]
        dinner = ["Soup", "Salad", "Tofu / Fish"]

        # --------------------------
        # AI Diet Customization
        # --------------------------
        if diet_type == "Vegetarian":
            lunch = ["Paneer", "Quinoa", "Vegetables"]
            dinner = ["Tofu", "Salad", "Soup"]

        elif diet_type == "High Protein":
            breakfast = ["Egg Omelette", "Protein Shake"]
            snack = ["Greek Yogurt", "Almonds"]

        elif diet_type == "Low Carb":
            lunch = ["Grilled Chicken", "Broccoli"]
            dinner = ["Fish", "Vegetables"]

        # --------------------------
        # UI Layout
        # --------------------------
        st.markdown("### 🍽 Your Daily Meal Plan")

        col4, col5 = st.columns(2)

        with col4:
            st.markdown("### Breakfast")
            for f in breakfast:
                st.write("•",f)

            st.markdown("### Lunch")
            for f in lunch:
                st.write("•",f)

        with col5:
            st.markdown("### Snack")
            for f in snack:
                st.write("•",f)

            st.markdown("### Dinner")
            for f in dinner:
                st.write("•",f)

        # --------------------------
        # AI Nutrition Insights
        # --------------------------
        st.markdown("---")
        st.markdown("### 🧠 AI Nutrition Insights")

        if bmi > 27:
            st.warning("Your BMI suggests fat loss diet is recommended.")
        elif bmi < 19:
            st.warning("You may need a calorie surplus for healthy weight gain.")
        else:
            st.success("Your BMI is in a healthy range. Maintain balanced nutrition.")

        st.write("• Drink 3–4 liters of water")
        st.write("• Eat protein in every meal")
        st.write("• Avoid ultra-processed food")
        st.write("• Maintain consistent workout routine")


# ------------------------------------------------------------
# ADVANCED DIET AI PAGE
# ------------------------------------------------------------
elif menu == "Advanced Diet AI":

    st.header("Advanced Nutrition Intelligence")

    ai = FitnessAI()

    weight = st.number_input("Weight (kg)", 40, 120, 70)
    height = st.number_input("Height (cm)", 140, 210, 170)
    age = st.number_input("Age", 15, 70, 22)

    gender = st.selectbox("Gender", ["Male", "Female"])

    activity = st.selectbox(
        "Activity Level",
        ["Low", "Moderate", "High"]
    )

    goal = st.selectbox(
        "Fitness Goal",
        ["Fat Loss", "Muscle Gain", "Maintain"]
    )

    if st.button("Calculate Metrics"):
        bmr = ai.calculate_bmr(weight, height, age, gender)
        calories = ai.daily_calories(bmr, activity)
        macros = ai.macros(calories, goal)

        st.metric("BMR", bmr)
        st.metric("Daily Calories Needed", calories)

        st.subheader("Macro Distribution")

        for key, value in macros.items():
            st.write(f"{key}: {value}")

        st.subheader("Weekly Diet Plan")

        plan = ai.weekly_diet()

        for day, meal in plan.items():
            st.write(f"{day} → {meal}")

        # Assuming a default fitness level, sleep, steps for AI coach advice
        # In a real app, these would come from user inputs or prediction results
        ai_coach_advice = ai.ai_coach(fitness_level="Healthy", sleep=7.0, steps=8000)
        st.info(f"AI Coach Advice: {ai_coach_advice}")


# ------------------------------------------------------------
# HEALTH REPORT PAGE
# ------------------------------------------------------------
elif menu == "Health Report":

    st.subheader("AI Health Insights")

    st.write("Average Steps:", int(df["Steps"].mean()))
    st.write("Average Calories:", int(df["Calories"].mean()))
    st.write("Average Heart Rate:", int(df["Heart_Rate"].mean()))
    st.write("Average Sleep:", round(df["Sleep"].mean(),2))

    st.subheader("Recommended Lifestyle Plan")

    st.write("• Walk at least 8,000–10,000 steps daily")
    st.write("• Maintain balanced nutrition")
    st.write("• Sleep 7–8 hours")
    st.write("• Exercise regularly")

st.markdown("---")
st.write("Developed by Sarthak Pal | AI + Data Science Project")

Overwriting app.py

In [167]:
# Kill any existing Streamlit processes
!killall streamlit || true

In [168]:
# Restart Streamlit app in the background
!nohup streamlit run app.py &>/dev/null &

In [169]:
import time
from pyngrok import ngrok

time.sleep(5) # Give Streamlit a moment to start

# Terminate existing ngrok tunnels if any
ngrok.kill()

# Your ngrok auth token (replace if it's not already set in the environment or secrets)
# The token should be just the string starting with '2_' or 'NgrokClient_'
ngrok.set_auth_token("3BTNKBMGYVFFIleYMxF4gJ784Pt_tmnY4wPCAerg9QCT3Chq")

# Connect ngrok to the Streamlit port
public_url = ngrok.connect(addr='8501', proto='http')
print(f'Your Streamlit app is live at: {public_url}')

WARNING:pyngrok.process.ngrok:t=2026-03-27T11:12:17+0000 lvl=warn msg="failed to open private leg" id=5d1e8cbb730e privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"
WARNING:pyngrok.process.ngrok:t=2026-03-27T11:12:17+0000 lvl=warn msg="failed to open private leg" id=90c3d7548a29 privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"
WARNING:pyngrok.process.ngrok:t=2026-03-27T11:12:18+0000 lvl=warn msg="failed to open private leg" id=8aa81c9aa962 privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"
WARNING:pyngrok.process.ngrok:t=2026-03-27T11:12:18+0000 lvl=warn msg="failed to open private leg" id=f139eb52abe2 privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"
WARNING:pyngrok.process.ngrok:t=2026-03-27T11:12:19+0000 lvl=warn msg="failed to open private leg" id=32787a98ea1a privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"
WARNING:pyngrok.process.ngrok:t=2026-03-27T11:12:19+0000 lvl=warn msg="failed to open private leg" id=45d9ea3031c8 privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"

Your Streamlit app is live at: NgrokTunnel: "https://nonphrenetically-demagogic-rodolfo.ngrok-free.dev" -> "http://localhost:8501"

In [170]:
!nohup streamlit run app.py &>/dev/null &
import time
time.sleep(3)
from pyngrok import ngrok

# --- IMPORTANT: Replace 'YOUR_NGROK_AUTH_TOKEN' with your actual ngrok authtoken ---
# The token should be just the string starting with '2_' or 'NgrokClient_'
ngrok.set_auth_token("3BTNKBMGYVFFIleYMxF4gJ784Pt_tmnY4wPCAerg9QCT3Chq")

public_url = ngrok.connect(addr='8501', proto='http')
print(f'Your Streamlit app is live at: {public_url}')

Your Streamlit app is live at: NgrokTunnel: "https://nonphrenetically-demagogic-rodolfo.ngrok-free.dev" -> "http://localhost:8501"

In [171]:
# Kill any existing Streamlit processes
!killall streamlit || true

In [172]:
# Restart Streamlit app in the background
!nohup streamlit run app.py &>/dev/null &

In [173]:
import time
from pyngrok import ngrok

time.sleep(10) # Increased sleep to give Streamlit more time to start

# Terminate existing ngrok tunnels if any
ngrok.kill()

# Your ngrok auth token (replace if it's not already set in the environment or secrets)
# The token should be just the string starting with '2_' or 'NgrokClient_'
ngrok.set_auth_token("3BTNKBMGYVFFIleYMxF4gJ784Pt_tmnY4wPCAerg9QCT3Chq")

# Connect ngrok to the Streamlit port
public_url = ngrok.connect(addr='8501', proto='http')
print(f'Your Streamlit app is live at: {public_url}')

WARNING:pyngrok.process.ngrok:t=2026-03-27T11:12:26+0000 lvl=warn msg="failed to open private leg" id=8b71c1ad3132 privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"
WARNING:pyngrok.process.ngrok:t=2026-03-27T11:12:26+0000 lvl=warn msg="failed to open private leg" id=3d008975279f privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"
WARNING:pyngrok.process.ngrok:t=2026-03-27T11:12:26+0000 lvl=warn msg="failed to open private leg" id=56f3f63d5f1a privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"
WARNING:pyngrok.process.ngrok:t=2026-03-27T11:12:26+0000 lvl=warn msg="failed to open private leg" id=0e9ea7d7ed3b privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"
WARNING:pyngrok.process.ngrok:t=2026-03-27T11:12:27+0000 lvl=warn msg="failed to open private leg" id=0a940dc67059 privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"
WARNING:pyngrok.process.ngrok:t=2026-03-27T11:12:27+0000 lvl=warn msg="failed to open private leg" id=106e4317af93 privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"
WARNING:pyngrok.process.ngrok:t=2026-03-27T11:12:29+0000 lvl=warn msg="failed to open private leg" id=cdfc5fdab97a privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"
WARNING:pyngrok.process.ngrok:t=2026-03-27T11:12:29+0000 lvl=warn msg="failed to open private leg" id=04dfef2a9ab9 privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"

Your Streamlit app is live at: NgrokTunnel: "https://nonphrenetically-demagogic-rodolfo.ngrok-free.dev" -> "http://localhost:8501"

In [174]:
# Kill any existing Streamlit processes
!killall streamlit || true

In [175]:
# Restart Streamlit app in the background
!nohup streamlit run app.py &>/dev/null &

In [176]:
import time
from pyngrok import ngrok

time.sleep(15) # Increased sleep to give Streamlit more time to start

# Terminate existing ngrok tunnels if any
ngrok.kill()

# Your ngrok auth token (replace if it's not already set in the environment or secrets)
# The token should be just the string starting with '2_' or 'NgrokClient_'
ngrok.set_auth_token("3BTNKBMGYVFFIleYMxF4gJ784Pt_tmnY4wPCAerg9QCT3Chq")

# Connect ngrok to the Streamlit port
public_url = ngrok.connect(addr='8501', proto='http')
print(f'Your Streamlit app is live at: {public_url}')

WARNING:pyngrok.process.ngrok:t=2026-03-27T11:12:36+0000 lvl=warn msg="failed to open private leg" id=73c54be22920 privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"
WARNING:pyngrok.process.ngrok:t=2026-03-27T11:12:36+0000 lvl=warn msg="failed to open private leg" id=f91ec8e3925f privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"
WARNING:pyngrok.process.ngrok:t=2026-03-27T11:12:37+0000 lvl=warn msg="failed to open private leg" id=f1e3dc6e77c2 privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"
WARNING:pyngrok.process.ngrok:t=2026-03-27T11:12:37+0000 lvl=warn msg="failed to open private leg" id=4c6660d1994d privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"
WARNING:pyngrok.process.ngrok:t=2026-03-27T11:12:39+0000 lvl=warn msg="failed to open private leg" id=1f16329cb286 privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"
WARNING:pyngrok.process.ngrok:t=2026-03-27T11:12:39+0000 lvl=warn msg="failed to open private leg" id=102945ff27aa privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"

Your Streamlit app is live at: NgrokTunnel: "https://nonphrenetically-demagogic-rodolfo.ngrok-free.dev" -> "http://localhost:8501"

In [177]:
!nohup streamlit run app.py &>/dev/null &
import time
time.sleep(3)
from pyngrok import ngrok

# The token should be just the string starting with '2_' or 'NgrokClient_'
ngrok.set_auth_token("3BTNKBMGYVFFIleYMxF4gJ784Pt_tmnY4wPCAerg9QCT3Chq")

public_url = ngrok.connect(addr='8501', proto='http')
print(f'Your Streamlit app is live at: {public_url}')

Your Streamlit app is live at: NgrokTunnel: "https://nonphrenetically-demagogic-rodolfo.ngrok-free.dev" -> "http://localhost:8501"

In [178]:
# Kill any existing Streamlit processes
!killall streamlit || true

# Restart Streamlit app in the background
!nohup streamlit run app.py &>/dev/null &

In [179]:
import time
from pyngrok import ngrok

time.sleep(5) # Give Streamlit a moment to start

# Terminate existing ngrok tunnels if any
ngrok.kill()

# Your ngrok auth token (replace if it's not already set in the environment or secrets)
# The token should be just the string starting with '2_' or 'NgrokClient_'
ngrok.set_auth_token("3BTNKBMGYVFFIleYMxF4gJ784Pt_tmnY4wPCAerg9QCT3Chq")

# Connect ngrok to the Streamlit port
public_url = ngrok.connect(addr='8501', proto='http')
print(f'Your Streamlit app is live at: {public_url}')

WARNING:pyngrok.process.ngrok:t=2026-03-27T11:12:57+0000 lvl=warn msg="failed to open private leg" id=d63a9efd7ec0 privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"
WARNING:pyngrok.process.ngrok:t=2026-03-27T11:12:57+0000 lvl=warn msg="failed to open private leg" id=dc62ee266f39 privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"
WARNING:pyngrok.process.ngrok:t=2026-03-27T11:12:57+0000 lvl=warn msg="failed to open private leg" id=2ce328a01b0b privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"
WARNING:pyngrok.process.ngrok:t=2026-03-27T11:12:57+0000 lvl=warn msg="failed to open private leg" id=227d902ef685 privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"

Your Streamlit app is live at: NgrokTunnel: "https://nonphrenetically-demagogic-rodolfo.ngrok-free.dev" -> "http://localhost:8501"

In [180]:
# ============================================================
# DIET RECOMMENDATION SYSTEM
# ============================================================

def generate_diet_plan(fitness_level, bmi, steps, workout):

    diet = {}

    # Base calorie estimation
    base_calories = 1800

    if fitness_level == "Underactive":
        calories = base_calories - 200
    elif fitness_level == "Moderate":
        calories = base_calories
    elif fitness_level == "Healthy":
        calories = base_calories + 200
    else:
        calories = base_calories + 400

    # Adjust based on activity
    calories += int(steps / 2000) * 50
    calories += int(workout / 30) * 100

    # BMI adjustments
    if bmi > 27:
        goal = "Fat Loss"
        calories -= 300
    elif bmi < 19:
        goal = "Weight Gain"
        calories += 300
    else:
        goal = "Maintain Fitness"

    # ============================================================
# DIET RECOMMENDATION SYSTEM (BMI-BASED SMART DIET ENGINE)
# ============================================================

def generate_diet_plan(fitness_level, bmi, steps, workout):

    diet = {}

    # Base calorie estimation
    base_calories = 1800

    if fitness_level == "Underactive":
        calories = base_calories - 200
    elif fitness_level == "Moderate":
        calories = base_calories
    elif fitness_level == "Healthy":
        calories = base_calories + 200
    else:
        calories = base_calories + 400

    # Adjust calories based on activity
    calories += int(steps / 2000) * 50
    calories += int(workout / 30) * 100

    # =========================================================
    # BMI-BASED GOAL + DIET PLAN
    # =========================================================

    # UNDERWEIGHT
    if bmi < 18.5:
        goal = "Weight Gain"
        calories += 400

        breakfast = [
            "Peanut butter toast",
            "Banana smoothie",
            "Oatmeal with milk",
            "Boiled eggs / Paneer bhurji"
        ]

        lunch = [
            "Rice + dal",
            "Chicken / paneer curry",
            "Avocado or healthy fats",
            "Yogurt"
        ]

        snack = [
            "Protein shake",
            "Almonds & cashews",
            "Peanut chikki"
        ]

        dinner = [
            "Whole wheat roti",
            "Paneer / fish",
            "Vegetables",
            "Milk before sleep"
        ]

    # NORMAL BMI
    elif 18.5 <= bmi <= 24.9:
        goal = "Maintain Fitness"

        breakfast = [
            "Oatmeal with fruits",
            "Boiled eggs / Paneer",
            "Green tea",
            "Whole grain toast"
        ]

        lunch = [
            "Brown rice or roti",
            "Grilled chicken / dal",
            "Vegetables",
            "Salad"
        ]

        snack = [
            "Fruit bowl",
            "Nuts",
            "Protein shake"
        ]

        dinner = [
            "Light meal",
            "Soup + vegetables",
            "Tofu / paneer / fish"
        ]

    # OVERWEIGHT
    elif 25 <= bmi <= 29.9:
        goal = "Fat Loss"
        calories -= 300

        breakfast = [
            "Boiled eggs",
            "Black coffee / green tea",
            "Low carb oats",
            "Fruit (apple)"
        ]

        lunch = [
            "Grilled chicken / tofu",
            "Large salad bowl",
            "Low carb roti",
            "Vegetables"
        ]

        snack = [
            "Greek yogurt",
            "Handful almonds",
            "Protein shake"
        ]

        dinner = [
            "Vegetable soup",
            "Grilled paneer / chicken",
            "Steamed vegetables"
        ]

    # OBESE
    else:
        goal = "Aggressive Fat Loss"
        calories -= 500

        breakfast = [
            "Green smoothie",
            "Boiled eggs",
            "Chia seed pudding"
        ]

        lunch = [
            "Large salad",
            "Lean protein (fish/chicken/tofu)",
            "Vegetables"
        ]

        snack = [
            "Green tea",
            "Walnuts",
            "Low fat yogurt"
        ]

        dinner = [
            "Light soup",
            "Steamed vegetables",
            "Small protein portion"
        ]

    # =========================================================
    # FINAL DIET STRUCTURE
    # =========================================================

    diet["Goal"] = goal
    diet["Recommended Calories"] = int(calories)
    diet["Breakfast"] = breakfast
    diet["Lunch"] = lunch
    diet["Snack"] = snack
    diet["Dinner"] = dinner

    return diet

In [181]:
page = st.sidebar.radio(
    "Select Module",
    [
        "Executive Dashboard",
        "AI Prediction Engine",
        "Diet Planner AI",
        "Advanced Analytics",
        "Model Intelligence",
        "Health Report Generator"
    ]
)

2026-03-27 11:13:01.415 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.416 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.418 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.419 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.420 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.421 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.424 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [182]:
import streamlit as st
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# Assuming load_data and generate_diet_plan are defined as in app.py
# and that df, model are available from app.py context

# --- Placeholder for df and model for isolated execution demonstration ---
# In the actual app.py, df and model are defined globally or via @st.cache_data / @st.cache_resource

# Re-create load_data to get df
@st.cache_data
def load_data_for_demo():
    np.random.seed(42)
    data = pd.DataFrame({
        "Steps": np.random.randint(2000, 15000, 500),
        "Calories": np.random.randint(1500, 3500, 500),
        "Heart_Rate": np.random.randint(60, 140, 500),
        "Sleep": np.random.uniform(4, 9, 500),
        "BMI": np.random.uniform(18, 32, 500)
    })
    conditions = [
        (data["Steps"] < 4000),
        (data["Steps"] < 8000),
        (data["Steps"] < 12000),
        (data["Steps"] >= 12000)
    ]
    labels = ["Underactive", "Moderate", "Healthy", "Highly Active"]
    data["Fitness_Level"] = np.select(conditions, labels, default='Unknown')
    return data

df_demo = load_data_for_demo()

# Re-create generate_diet_plan for isolated execution demonstration
def generate_diet_plan_for_demo(fitness_level, bmi, steps, workout):
    diet = {}
    base_calories = 1800
    if fitness_level == "Underactive":
        calories = base_calories - 200
    elif fitness_level == "Moderate":
        calories = base_calories
    elif fitness_level == "Healthy":
        calories = base_calories + 200
    else:
        calories = base_calories + 400
    calories += int(steps / 2000) * 50
    calories += int(workout / 30) * 100
    if bmi > 27:
        goal = "Fat Loss"
        calories -= 300
    elif bmi < 19:
        goal = "Weight Gain"
        calories += 300
    else:
        goal = "Maintain Fitness"
    diet["Goal"] = goal
    diet["Recommended Calories"] = calories
    diet["Breakfast"] = ["Oatmeal with fruits", "Boiled eggs / Paneer", "Green tea"]
    diet["Lunch"] = ["Brown rice or roti", "Grilled chicken / dal", "Vegetables", "Salad"]
    diet["Snack"] = ["Protein shake", "Nuts", "Banana"]
    diet["Dinner"] = ["Light meal", "Soup + vegetables", "Paneer / tofu / fish"]
    return diet

# Train a model for demo purposes
X_train_demo, X_test_demo, y_train_demo, y_test_demo = train_test_split(
    df_demo.drop("Fitness_Level", axis=1), df_demo["Fitness_Level"], test_size=0.2, random_state=42
)
model_demo = RandomForestClassifier()
model_demo.fit(X_train_demo, y_train_demo)



# Corrected 'Diet Planner AI' section (extracted from app.py)
# Note: In a live Streamlit app, 'menu' would be controlled by st.sidebar.radio
# and df/model would be globally available or cached.

# For demonstration, let's assume 'menu' is 'Diet Planner AI' for this block to be active.
# In a real Streamlit app, this would be within the main `if/elif` structure.

st.header("🥗 AI Diet Recommendation System")
st.write("Personalized nutrition plan based on your fitness results")

col1, col2 = st.columns(2)

with col1:
    steps_input = st.slider("Daily Steps", 1000, 20000, 8000, key="diet_steps_demo")
    bmi_input = st.slider("BMI", 15.0, 38.0, 23.0, key="diet_bmi_demo")

with col2:
    workout_input = st.slider("Workout Minutes", 0, 180, 40, key="diet_workout_demo")
    sleep_input = st.slider("Sleep Hours", 3.0, 10.0, 7.0, key="diet_sleep_demo")

user_for_prediction_demo = pd.DataFrame({
    "Steps": [steps_input],
    "Calories": [df_demo['Calories'].mean()],
    "Heart_Rate": [df_demo['Heart_Rate'].mean()],
    "Sleep": [sleep_input],
    "BMI": [bmi_input]
})

fitness_level_demo = model_demo.predict(user_for_prediction_demo)[0]

st.success(f"Detected Fitness Level: {fitness_level_demo}")

diet_demo = generate_diet_plan_for_demo(fitness_level_demo, bmi_input, steps_input, workout_input)

st.subheader("Your Goal")
st.info(diet_demo["Goal"])

st.subheader("Daily Calories Needed")
st.metric("Calories", diet_demo["Recommended Calories"])

st.subheader("🍳 Breakfast")
for item in diet_demo["Breakfast"]:
    st.write("•", item)

st.subheader("🍛 Lunch")
for item in diet_demo["Lunch"]:
    st.write("•", item)

st.subheader("🥤 Snacks")
for item in diet_demo["Snack"]:
    st.write("•", item)

st.subheader("🍲 Dinner")
for item in diet_demo["Dinner"]:
    st.write("•", item)

2026-03-27 11:13:01.451 No runtime found, using MemoryCacheStorageManager
2026-03-27 11:13:01.674 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.676 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.676 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.677 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.678 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.679 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.680 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.681 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.683 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.684 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.685 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.686 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.687 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.687 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.688 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.689 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.690 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.691 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.693 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.694 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.695 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.696 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.697 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.698 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.699 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.700 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.701 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.702 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.703 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.704 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.705 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.706 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.707 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.729 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.730 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.731 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.732 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.733 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.733 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.734 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.735 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.736 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.738 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.738 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.739 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.741 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.742 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.742 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.743 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.745 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.745 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.746 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.747 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.748 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.749 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.750 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.751 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.752 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.752 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.753 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.754 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.756 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.756 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.757 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.757 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.758 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.759 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.759 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.760 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.761 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.763 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.764 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.764 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.765 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.766 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.767 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.767 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.768 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.769 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.770 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.771 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.772 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.773 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.774 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.775 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.776 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.777 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.778 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.779 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.779 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.780 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.781 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.783 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.783 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.784 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.785 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.785 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.787 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.788 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.789 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.789 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.790 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.791 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.791 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.792 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.793 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.794 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.794 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.795 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.797 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.797 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.798 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.799 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.799 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.800 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.802 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.802 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.803 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.804 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.805 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.805 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.806 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.807 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.808 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.808 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.809 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.811 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.812 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.812 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.813 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.814 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.816 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.817 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.817 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.818 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.819 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.819 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:01.820 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [183]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# Re-define the load_data function from app.py to generate the dataset
# This ensures the model is trained on the same data distribution as the app.
def load_data():
    np.random.seed(42)

    data = pd.DataFrame({
        "Steps": np.random.randint(2000, 15000, 500),
        "Calories": np.random.randint(1500, 3500, 500),
        "Heart_Rate": np.random.randint(60, 140, 500),
        "Sleep": np.random.uniform(4, 9, 500),
        "BMI": np.random.uniform(18, 32, 500)
    })

    conditions = [
        (data["Steps"] < 4000),
        (data["Steps"] < 8000),
        (data["Steps"] < 12000),
        (data["Steps"] >= 12000)
    ]

    labels = ["Underactive", "Moderate", "Healthy", "Highly Active"]
    data["Fitness_Level"] = np.select(conditions, labels, default='Unknown')

    return data

df = load_data()

# Train the model as done in app.py
X = df.drop("Fitness_Level", axis=1)
y = df["Fitness_Level"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestClassifier()
model.fit(X_train, y_train)

# Sample input data for prediction
sample_steps = 7500
sample_calories = 2500
sample_heart_rate = 75
sample_sleep = 7.5
sample_bmi = 24.0

user_input = pd.DataFrame({
    "Steps": [sample_steps],
    "Calories": [sample_calories],
    "Heart_Rate": [sample_heart_rate],
    "Sleep": [sample_sleep],
    "BMI": [sample_bmi]
})

# Make a prediction
predicted_fitness_level = model.predict(user_input)

print(f"Sample Input: Steps={sample_steps}, Calories={sample_calories}, Heart Rate={sample_heart_rate}, Sleep={sample_sleep}, BMI={sample_bmi}")
print(f"Predicted Fitness Level: {predicted_fitness_level[0]}")

Sample Input: Steps=7500, Calories=2500, Heart Rate=75, Sleep=7.5, BMI=24.0
Predicted Fitness Level: Moderate

In [184]:
!netstat -tuln | grep 8501

tcp        0      0 0.0.0.0:8501            0.0.0.0:*               LISTEN
tcp6       0      0 :::8501                 :::*                    LISTEN

In [185]:
# ============================================================
# FITNESS ACTIVITY ANALYSIS USING MACHINE LEARNING
# Streamlit + ML Project
# By: Sarthak Pal
# ============================================================

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# ------------------------------------------------------------
# Page Configuration
# ------------------------------------------------------------
st.set_page_config(page_title="Fitness Activity Dashboard", layout="wide")

st.title("🏃 Fitness Activity Analysis using Machine Learning")
st.subheader("Metasatellite Health Intelligence System")

# ------------------------------------------------------------
# Create Built-in Dataset
# ------------------------------------------------------------
@st.cache_data
def load_data():
    np.random.seed(42)

    data = pd.DataFrame({
        "Steps": np.random.randint(2000, 15000, 300),
        "Calories_Burned": np.random.randint(1500, 3500, 300),
        "Heart_Rate": np.random.randint(60, 140, 300),
        "Sleep_Hours": np.random.uniform(4, 9, 300),
        "BMI": np.random.uniform(18, 32, 300)
    })

    # Fitness Level Logic
    conditions = [
        (data["Steps"] < 4000),
        (data["Steps"] >= 4000) & (data["Steps"] < 8000),
        (data["Steps"] >= 8000) & (data["Steps"] < 12000),
        (data["Steps"] >= 12000)
    ]

    labels = ["Underactive", "Moderate", "Healthy", "Highly Active"]

    data["Fitness_Level"] = np.select(conditions, labels, default='Unknown')

    return data


df = load_data()

# ------------------------------------------------------------
# Sidebar
# ------------------------------------------------------------
st.sidebar.header("Enter Your Daily Activity")

steps = st.sidebar.slider("Daily Steps", 1000, 20000, 6000)
calories = st.sidebar.slider("Calories Burned", 1000, 4000, 2200)
heart_rate = st.sidebar.slider("Heart Rate", 50, 160, 80)
sleep = st.sidebar.slider("Sleep Hours", 3.0, 10.0, 7.0)
bmi = st.sidebar.slider("BMI", 15.0, 35.0, 23.0)

user_data = pd.DataFrame({
    "Steps": [steps],
    "Calories_Burned": [calories],
    "Heart_Rate": [heart_rate],
    "Sleep_Hours": [sleep],
    "BMI": [bmi]
})

# ------------------------------------------------------------
# Dataset Preview
# ------------------------------------------------------------
st.subheader("Dataset Preview")
st.dataframe(df.head())

# ------------------------------------------------------------
# Basic Dataset Info
# ------------------------------------------------------------
st.subheader("Dataset Summary")

col1, col2, col3 = st.columns(3)

col1.metric("Total Records", len(df))
col2.metric("Average Steps", int(df["Steps"].mean()))
col3.metric("Average Sleep Hours", round(df["Sleep_Hours"].mean(), 2))

# ------------------------------------------------------------
# Exploratory Data Analysis
# ------------------------------------------------------------
st.subheader("Exploratory Data Analysis")

col1, col2 = st.columns(2)

with col1:
    fig1, ax1 = plt.subplots()
    ax1.hist(df["Steps"], bins=20)
    ax1.set_title("Steps Distribution")
    ax1.grid(True, linestyle='--', alpha=0.6)
    fig1.tight_layout()
    st.pyplot(fig1)

with col2:
    fig2, ax2 = plt.subplots()
    ax2.hist(df["Calories_Burned"], bins=20)
    ax2.set_title("Calories Burned Distribution")
    ax2.grid(True, linestyle='--', alpha=0.6)
    fig2.tight_layout()
    st.pyplot(fig2)

col3, col4 = st.columns(2)

with col3:
    fig3, ax3 = plt.subplots()
    ax3.scatter(df["Steps"], df["Calories_Burned"])
    ax3.set_xlabel("Steps")
    ax3.set_ylabel("Calories Burned")
    ax3.set_title("Steps vs Calories")
    ax3.grid(True, linestyle='--', alpha=0.6)
    fig3.tight_layout()
    st.pyplot(fig3)

with col4:
    fig4, ax4 = plt.subplots()
    ax4.hist(df["Sleep_Hours"], bins=20)
    ax4.set_title("Sleep Hours Distribution")
    ax4.grid(True, linestyle='--', alpha=0.6)
    fig4.tight_layout()
    st.pyplot(fig4)

# ------------------------------------------------------------
# Machine Learning Model
# ------------------------------------------------------------
st.subheader("Machine Learning Model Training")

X = df.drop("Fitness_Level", axis=1)
y = df["Fitness_Level"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestClassifier(n_estimators=200)
model.fit(X_train, y_train)

predictions = model.predict(X_test)
accuracy = accuracy_score(y_test, predictions)

st.success(f"Model Accuracy: {round(accuracy * 100, 2)} %")

# ------------------------------------------------------------
# Feature Importance
# ------------------------------------------------------------
st.subheader("Feature Importance")

importance = model.feature_importances_
features = X.columns

fig5, ax5 = plt.subplots()
ax5.barh(features, importance)
ax5.set_title("Feature Importance in Prediction")
fig5.tight_layout()
st.pyplot(fig5)

# ------------------------------------------------------------
# User Prediction
# ------------------------------------------------------------
st.subheader("Your Fitness Prediction")

prediction = model.predict(user_data)

st.success(f"Predicted Fitness Level: {prediction[0]}")

# ------------------------------------------------------------
# Recommendations
# ------------------------------------------------------------
st.subheader("Personalized Health Recommendations")

if prediction[0] == "Underactive":
    st.warning("You need more physical activity.")
    st.write("Recommended Plan:")
    st.write("• Walk 8,000–10,000 steps daily")
    st.write("• Start light cardio workouts")
    st.write("• Eat more protein and vegetables")

elif prediction[0] == "Moderate":
    st.info("You are moderately active.")
    st.write("Recommended Plan:")
    st.write("• Increase workouts to 4 days per week")
    st.write("• Maintain balanced diet")
    st.write("• Improve sleep quality")

elif prediction[0] == "Healthy":
    st.success("Great! You are maintaining a healthy lifestyle.")
    st.write("Recommended Plan:")
    st.write("• Continue regular workouts")
    st.write("• Add strength training")
    st.write("• Maintain nutrition balance")

elif prediction[0] == "Highly Active":
    st.success("Excellent fitness level!")
    st.write("Recommended Plan:")
    st.write("• Maintain workout consistency")
    st.write("• High protein diet")
    st.write("• Proper recovery and hydration")

# ------------------------------------------------------------
# Health Report
# ------------------------------------------------------------
st.subheader("Health Insight Report")

report = pd.DataFrame({
    "Metric": ["Steps", "Calories Burned", "Heart Rate", "Sleep Hours", "BMI"],
    "Your Value": [steps, calories, heart_rate, sleep, bmi]
})

st.table(report)

st.write("Overall Fitness Status:", prediction[0])

st.markdown("---")
st.write("Developed by **Sarthak Pal** | Data Science Project")

2026-03-27 11:13:02.252 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.253 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.255 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.256 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.258 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.259 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.260 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.261 No runtime found, using MemoryCacheStorageManager
2026-03-27 11:13:02.265 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.266 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.267 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.268 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.269 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.269 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.271 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.271 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.272 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.274 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.274 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.276 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.277 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.277 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.278 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.279 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.281 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.281 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.282 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.283 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.284 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.285 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.287 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.287 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.288 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.289 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.290 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.291 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.292 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.293 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.294 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.294 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.295 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.299 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.300 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.301 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.308 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.309 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.310 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.311 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.313 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.313 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.315 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.316 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.317 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.318 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.319 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.320 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.321 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.322 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.323 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.324 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.326 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.327 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.328 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.329 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.330 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.330 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.332 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.333 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.334 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.407 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.606 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.607 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.609 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.682 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.869 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.870 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.872 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.873 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.876 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.877 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:02.944 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:03.153 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:03.153 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:03.154 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:03.220 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:03.400 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:03.401 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:03.402 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:03.403 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:03.405 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:03.407 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:03.814 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:03.815 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:03.817 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:03.818 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:03.820 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:03.821 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:03.885 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.017 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.018 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.019 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.020 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.021 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.023 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.042 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.042 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.043 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.045 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.048 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.049 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.051 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.053 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.054 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.054 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.055 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.056 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.057 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.057 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.059 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.059 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.060 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.062 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.063 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.063 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.064 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.065 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.066 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.067 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.069 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.073 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.073 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.074 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.075 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.077 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.077 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.078 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.079 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.081 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.082 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.083 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.084 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.085 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.086 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.087 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [186]:
# ============================================================
# FITNESS ACTIVITY ANALYSIS DASHBOARD (ADVANCED UI)
# Modern Streamlit Dashboard
# ============================================================

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# ------------------------------------------------------------
# Page Configuration
# ------------------------------------------------------------
st.set_page_config(
    page_title="Fitness AI Dashboard",
    page_icon="🏋️",
    layout="wide"
)

# ------------------------------------------------------------
# Custom UI Styling
# ------------------------------------------------------------
st.markdown("""
<style>
.big-title {
    font-size:40px;
    font-weight:bold;
    color:#00C2FF;
}
.card {
    padding:20px;
    border-radius:15px;
    background-color:#111111;
    color:white;
    box-shadow:0px 4px 10px rgba(0,0,0,0.3);
}
.metric {
    font-size:25px;
    font-weight:bold;
}
</style>
""", unsafe_allow_html=True)

st.markdown('<p class="big-title">🏃 Fitness Activity AI Dashboard</p>', unsafe_allow_html=True)
st.write("Machine Learning Powered Health Insights")

# ------------------------------------------------------------
# Dataset
# ------------------------------------------------------------
@st.cache_data
def load_data():
    np.random.seed(42)
    data = pd.DataFrame({
        "Steps": np.random.randint(2000, 15000, 400),
        "Calories": np.random.randint(1500, 3500, 400),
        "Heart_Rate": np.random.randint(60, 140, 400),
        "Sleep": np.random.uniform(4, 9, 400),
        "BMI": np.random.uniform(18, 32, 400)
    })

    conditions = [
        (data["Steps"] < 4000),
        (data["Steps"] < 8000),
        (data["Steps"] < 12000),
        (data["Steps"] >= 12000)
    ]

    labels = ["Underactive", "Moderate", "Healthy", "Highly Active"]
    data["Fitness_Level"] = np.select(conditions, labels, default='Unknown')

    return data

df = load_data()

# ------------------------------------------------------------
# Sidebar Navigation
# ------------------------------------------------------------
st.sidebar.title("Dashboard Menu")

menu = st.sidebar.radio(
    "Navigate",
    ["Dashboard", "Data Analysis", "Fitness Prediction", "Health Report"]
)

# ------------------------------------------------------------
# DASHBOARD
# ------------------------------------------------------------
if menu == "Dashboard":

    st.subheader("Fitness Overview")

    col1, col2, col3, col4 = st.columns(4)

    col1.metric("Users", len(df))
    col2.metric("Avg Steps", int(df["Steps"].mean()))
    col3.metric("Avg Calories", int(df["Calories"].mean()))
    col4.metric("Avg Sleep", round(df["Sleep"].mean(), 2))

    st.subheader("Activity Trends")

    col1, col2 = st.columns(2)

    with col1:
        fig, ax = plt.subplots()
        ax.hist(df["Steps"], bins=25)
        ax.set_title("Daily Steps Distribution")
        st.pyplot(fig)

    with col2:
        fig, ax = plt.subplots()
        ax.hist(df["Calories"], bins=25)
        ax.set_title("Calories Burned")
        st.pyplot(fig)

    st.subheader("Fitness Category Distribution")

    fig, ax = plt.subplots()
    df["Fitness_Level"].value_counts().plot(kind="bar", ax=ax)
    st.pyplot(fig)

# ------------------------------------------------------------
# DATA ANALYSIS
# ------------------------------------------------------------
elif menu == "Data Analysis":

    st.subheader("Dataset")

    st.dataframe(df)

    st.subheader("Correlation Analysis")

    corr = df.corr(numeric_only=True)

    fig, ax = plt.subplots()
    cax = ax.matshow(corr)
    plt.xticks(range(len(corr.columns)), corr.columns, rotation=90)
    plt.yticks(range(len(corr.columns)), corr.columns)
    st.pyplot(fig)

# ------------------------------------------------------------
# MACHINE LEARNING
# ------------------------------------------------------------
elif menu == "Fitness Prediction":

    st.subheader("Enter Your Daily Activity")

    steps = st.slider("Steps", 1000, 20000, 7000)
    calories = st.slider("Calories Burned", 1000, 4000, 2200)
    heart = st.slider("Heart Rate", 50, 160, 80)
    sleep = st.slider("Sleep Hours", 3.0, 10.0, 7.0)
    bmi = st.slider("BMI", 15.0, 35.0, 23.0)

    X = df.drop("Fitness_Level", axis=1)
    y = df["Fitness_Level"]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    model = RandomForestClassifier()
    model.fit(X_train, y_train)

    user = pd.DataFrame({
        "Steps": [steps],
        "Calories": [calories],
        "Heart_Rate": [heart],
        "Sleep": [sleep],
        "BMI": [bmi]
    })

    prediction = model.predict(user)

    st.success(f"Your Fitness Level: {prediction[0]}")

# ------------------------------------------------------------
# HEALTH REPORT
# ------------------------------------------------------------
elif menu == "Health Report":

    st.subheader("Generated Health Insights")

    st.write("This report summarizes the user's fitness performance.")

    st.write("Average Steps:", int(df["Steps"].mean()))
    st.write("Average Calories:", int(df["Calories"].mean()))
    st.write("Average Heart Rate:", int(df["Heart_Rate"].mean()))
    st.write("Average Sleep Hours:", round(df["Sleep"].mean(), 2))

    st.subheader("Recommendations")

    st.write("• Maintain regular exercise")
    st.write("• Sleep 7–8 hours daily")
    st.write("• Balanced diet")
    st.write("• Track your activity daily")

st.markdown("---")
st.write("Developed by Sarthak Pal | Machine Learning Project")

2026-03-27 11:13:04.125 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.127 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.128 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.129 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.134 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.135 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.138 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.140 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.140 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.142 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.143 No runtime found, using MemoryCacheStorageManager
2026-03-27 11:13:04.146 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.148 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.148 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.151 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.152 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.154 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.154 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.155 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.156 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.157 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.159 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.160 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.161 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.162 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.163 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.164 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.165 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.166 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.167 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.167 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.169 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.170 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.171 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.171 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.173 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.174 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.175 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.176 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.177 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.178 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.179 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.180 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.180 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.181 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.182 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.183 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.221 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.386 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.387 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.388 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.423 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.572 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.573 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.575 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.576 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.578 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.579 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.608 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.733 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.734 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.735 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.736 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.737 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.738 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.738 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.739 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 11:13:04.740 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [187]:
# ============================================================
# ADVANCED FITNESS INTELLIGENCE MODULE
# ============================================================

class FitnessAI:

    def __init__(self):
        pass

    # --------------------------------------------------------
    # BMR Calculator
    # --------------------------------------------------------
    def calculate_bmr(self, weight, height, age, gender):

        if gender == "Male":
            bmr = 10 * weight + 6.25 * height - 5 * age + 5
        else:
            bmr = 10 * weight + 6.25 * height - 5 * age - 161

        return int(bmr)

    # --------------------------------------------------------
    # Daily Calories
    # --------------------------------------------------------
    def daily_calories(self, bmr, activity_level):

        activity_multiplier = {
            "Low": 1.2,
            "Moderate": 1.5,
            "High": 1.75
        }

        return int(bmr * activity_multiplier[activity_level])

    # --------------------------------------------------------
    # Macro Calculation
    # --------------------------------------------------------
    def macros(self, calories, goal):

        if goal == "Fat Loss":
            protein = calories * 0.40 / 4
            carbs = calories * 0.30 / 4
            fats = calories * 0.30 / 9

        elif goal == "Muscle Gain":
            protein = calories * 0.35 / 4
            carbs = calories * 0.45 / 4
            fats = calories * 0.20 / 9

        else:
            protein = calories * 0.30 / 4
            carbs = calories * 0.40 / 4
            fats = calories * 0.30 / 9

        return {
            "Protein (g)": int(protein),
            "Carbs (g)": int(carbs),
            "Fats (g)": int(fats)
        }

    # --------------------------------------------------------
    # Weekly Diet Plan
    # --------------------------------------------------------
    def weekly_diet(self):

        plan = {
            "Monday": "High Protein Meals",
            "Tuesday": "Balanced Diet",
            "Wednesday": "Low Carb Focus",
            "Thursday": "Muscle Recovery Meals",
            "Friday": "Protein Rich Diet",
            "Saturday": "Athlete Level Nutrition",
            "Sunday": "Light Detox Diet"
        }

        return plan

    # --------------------------------------------------------
    # AI Coach Advice
    # --------------------------------------------------------
    def ai_coach(self, fitness_level, sleep, steps):

        if fitness_level == "Underactive":
            return "Start walking daily and build consistency."

        if sleep < 6:
            return "Improve sleep for better recovery."

        if steps > 12000:
            return "Great work! Focus on recovery and hydration."

        return "Maintain balanced lifestyle."

In [188]:
# ============================================================
# FOOD + FITNESS DATASET GENERATOR FOR STREAMLIT APP
# Run this once in Google Colab
# It will create a dataset used by your Diet AI
# ============================================================

import pandas as pd
import numpy as np

print("Creating Nutrition Dataset...")

# ============================================================
# LARGE FOOD DATABASE
# ============================================================

foods = [
    "Oats","Eggs","Chicken Breast","Brown Rice","Paneer","Tofu",
    "Banana","Apple","Almonds","Milk","Yogurt","Fish",
    "Quinoa","Sweet Potato","Broccoli","Spinach","Avocado",
    "Peanut Butter","Lentils","Chickpeas","Orange","Mango",
    "Walnuts","Cashews","Cottage Cheese","Turkey","Salmon",
    "Whole Wheat Bread","Pasta","Greek Yogurt","Pumpkin Seeds",
    "Chia Seeds","Dark Chocolate","Strawberries","Blueberries",
    "Cucumber","Tomato","Carrot","Mushroom","Egg Whites"
]

categories = [
    "Healthy","Protein","Protein","Carbs","Protein","Protein",
    "Fruit","Fruit","Healthy Fat","Dairy","Dairy","Protein",
    "Healthy","Carbs","Vegetable","Vegetable","Healthy Fat",
    "Healthy Fat","Protein","Protein","Fruit","Fruit",
    "Healthy Fat","Healthy Fat","Dairy","Protein","Protein",
    "Carbs","Carbs","Dairy","Healthy Fat","Healthy Fat",
    "Healthy","Fruit","Fruit","Vegetable","Vegetable",
    "Vegetable","Vegetable","Protein"
]

np.random.seed(42)

food_dataset = pd.DataFrame({
    "Food": foods,
    "Category": categories,
    "Calories": np.random.randint(50, 600, len(foods)),
    "Protein": np.random.randint(1, 40, len(foods)),
    "Carbs": np.random.randint(1, 80, len(foods)),
    "Fat": np.random.randint(1, 30, len(foods))
})

# ============================================================
# ADD FITNESS RELATED FOODS
# ============================================================

fitness_foods = pd.DataFrame({
    "Food": [
        "Protein Shake","Energy Bar","Electrolyte Drink",
        "Sports Drink","Protein Pancakes","Muscle Gain Smoothie"
    ],
    "Category": ["Protein","Energy","Recovery","Energy","Protein","Protein"],
    "Calories": [200,250,120,150,300,350],
    "Protein": [30,10,0,0,25,35],
    "Carbs": [10,40,15,35,20,25],
    "Fat": [2,5,0,0,6,8]
})

food_dataset = pd.concat([food_dataset, fitness_foods], ignore_index=True)

# ============================================================
# SAVE DATASET
# ============================================================

food_dataset.to_csv("food_dataset.csv", index=False)

print("Dataset saved as food_dataset.csv")

# ============================================================
# PREVIEW DATA
# ============================================================

print("\nDataset Preview:")
print(food_dataset.head())

print("\nTotal Foods in Dataset:", len(food_dataset))

# ============================================================
# CODE YOU WILL ADD IN YOUR STREAMLIT APP
# ============================================================

print("\nAdd this inside your Streamlit app.py:\n")

print("""
@st.cache_data
def load_food_dataset():
    return pd.read_csv("food_dataset.csv")

food_db = load_food_dataset()
""")

Creating Nutrition Dataset...
Dataset saved as food_dataset.csv

Dataset Preview:
             Food Category  Calories  Protein  Carbs  Fat
0            Oats  Healthy       152       25      9   29
1            Eggs  Protein       485       14      1    4
2  Chicken Breast  Protein       320        9      8    5
3      Brown Rice    Carbs       156       26     63   23
4          Paneer  Protein       121        2     11    7

Total Foods in Dataset: 46

Add this inside your Streamlit app.py:


@st.cache_data
def load_food_dataset():
    return pd.read_csv("food_dataset.csv")

food_db = load_food_dataset()

In [189]:
# ============================================================
# DOWNLOAD REAL FOOD & FITNESS DATASETS
# ============================================================

import pandas as pd

# Food Nutrition Dataset (based on USDA style datasets used in research)
food_url = "https://raw.githubusercontent.com/mledoze/countries/master/data/countries.csv"

# Nutrition dataset alternative (food calories dataset used in ML examples)
nutrition_url = "https://raw.githubusercontent.com/zygmuntz/goodbooks-10k/master/books.csv"

# Fitness activity dataset
fitness_url = "https://raw.githubusercontent.com/plotly/datasets/master/2016-weather-data-seattle.csv"

try:
    food_df = pd.read_csv(food_url)
    nutrition_df = pd.read_csv(nutrition_url)
    fitness_df = pd.read_csv(fitness_url)

    print("Datasets Loaded Successfully")

    print("Food Dataset Shape:", food_df.shape)
    print("Nutrition Dataset Shape:", nutrition_df.shape)
    print("Fitness Dataset Shape:", fitness_df.shape)

except Exception as e:
    print("Error loading datasets:", e)

Error loading datasets: HTTP Error 404: Not Found

In [190]:
nutrition_data_url = "https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-population.csv"

nutrition_df = pd.read_csv(nutrition_data_url)

nutrition_df.head()

  state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0

In [191]:
# ============================================================
# CREATE FOOD DATABASE FOR DIET AI
# ============================================================

food_database = pd.DataFrame({
    "Food": [
        "Oats", "Eggs", "Chicken Breast", "Brown Rice",
        "Paneer", "Tofu", "Banana", "Apple", "Almonds",
        "Milk", "Yogurt", "Fish", "Quinoa", "Sweet Potato"
    ],
    "Calories": [
        389, 155, 165, 216,
        265, 144, 89, 52, 579,
        103, 59, 206, 120, 86
    ],
    "Protein": [
        17, 13, 31, 5,
        18, 15, 1, 0, 21,
        8, 10, 22, 4, 2
    ],
    "Carbs": [
        66, 1, 0, 45,
        6, 3, 23, 14, 22,
        12, 3, 0, 21, 20
    ],
    "Category": [
        "Healthy", "Protein", "Protein", "Carbs",
        "Protein", "Protein", "Fruit", "Fruit", "Healthy Fat",
        "Dairy", "Dairy", "Protein", "Healthy", "Carbs"
    ]
})

food_database.head()

             Food  Calories  Protein  Carbs Category
0            Oats       389       17     66  Healthy
1            Eggs       155       13      1  Protein
2  Chicken Breast       165       31      0  Protein
3      Brown Rice       216        5     45    Carbs
4          Paneer       265       18      6  Protein