<a href="https://colab.research.google.com/github/Sarthakpal23/fitness-tracker-/blob/main/fitness_analysis_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [64]:
!pip install streamlit
!pip install pyngrok

Requirement already satisfied: streamlit in /usr/local/lib/python3.12/dist-packages (1.55.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.3.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.46)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.0)
Requirement already satisfied: pandas<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.9.1)
Requirement already satisfied: protobuf<7,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.5.1)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.18.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.2.25)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Requirement already satisfied: pyngrok in /usr/local/lib/python3.12/dist-packages (7.5.1)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.12/dist-packages (from pyngrok) (6.0.3)

In [65]:
!pip install streamlit

Requirement already satisfied: streamlit in /usr/local/lib/python3.12/dist-packages (1.55.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.3.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.46)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.0)
Requirement already satisfied: pandas<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.9.1)
Requirement already satisfied: protobuf<7,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.5.1)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.18.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.2.25)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)

In [66]:
%%writefile app.py
# ============================================================
# ULTIMATE FITNESS AI DASHBOARD
# Advanced UI + Machine Learning + Analytics
# Developed by: Sarthak Pal
# ============================================================

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# ------------------------------------------------------------
# Page Setup
# ------------------------------------------------------------
st.set_page_config(
    page_title="Fitness AI Dashboard",
    page_icon="🏃",
    layout="wide"
)

# ------------------------------------------------------------
# Modern UI Styling
# ------------------------------------------------------------
st.markdown("""
<style>
.main-title {
    font-size:45px;
    font-weight:800;
    color:#00F5A0;
}

.card {
    background: rgba(255,255,255,0.05);
    padding:20px;
    border-radius:15px;
    backdrop-filter: blur(10px);
    box-shadow:0 4px 20px rgba(0,0,0,0.2);
}

.metric {
    font-size:28px;
    font-weight:bold;
}

.sidebar .sidebar-content {
    background: linear-gradient(180deg,#0f2027,#203a43,#2c5364);
}
</style>
""", unsafe_allow_html=True)

st.markdown('<p class="main-title">🏋️ AI Fitness Intelligence Dashboard</p>', unsafe_allow_html=True)
st.write("Machine Learning Powered Health Insights System")

# ------------------------------------------------------------
# Dataset Generator
# ------------------------------------------------------------
@st.cache_data
def load_data():
    np.random.seed(42)

    data = pd.DataFrame({
        "Steps": np.random.randint(2000, 15000, 500),
        "Calories": np.random.randint(1500, 3500, 500),
        "Heart_Rate": np.random.randint(60, 140, 500),
        "Sleep": np.random.uniform(4, 9, 500),
        "BMI": np.random.uniform(18, 32, 500)
    })

    conditions = [
        (data["Steps"] < 4000),
        (data["Steps"] < 8000),
        (data["Steps"] < 12000),
        (data["Steps"] >= 12000)
    ]

    labels = ["Underactive", "Moderate", "Healthy", "Highly Active"]

    data["Fitness_Level"] = np.select(conditions, labels, default='Unknown')

    return data

df = load_data()

# ------------------------------------------------------------
# Sidebar Navigation
# ------------------------------------------------------------
st.sidebar.title("Navigation")

menu = st.sidebar.radio(
    "Select Page",
    ["Dashboard", "Analytics", "Prediction AI", "Health Report"]
)

# ------------------------------------------------------------
# Fitness Score Function
# ------------------------------------------------------------
def fitness_score(steps, sleep, bmi):
    score = 0

    if steps > 10000:
        score += 40
    elif steps > 7000:
        score += 30
    else:
        score += 15

    if sleep >= 7:
        score += 30
    else:
        score += 15

    if 18.5 <= bmi <= 24.9:
        score += 30
    else:
        score += 15

    return score

# ------------------------------------------------------------
# DASHBOARD PAGE
# ------------------------------------------------------------
if menu == "Dashboard":

    st.subheader("System Overview")

    col1, col2, col3, col4 = st.columns(4)

    col1.metric("Total Records", len(df))
    col2.metric("Average Steps", int(df["Steps"].mean()))
    col3.metric("Average Calories", int(df["Calories"].mean()))
    col4.metric("Average Sleep", round(df["Sleep"].mean(), 2))

    st.subheader("Fitness Category Distribution")

    fig, ax = plt.subplots()
    df["Fitness_Level"].value_counts().plot(kind="bar", ax=ax)
    st.pyplot(fig)

# ------------------------------------------------------------
# ANALYTICS PAGE
# ------------------------------------------------------------
elif menu == "Analytics":

    st.subheader("Dataset Overview")

    st.dataframe(df)

    st.subheader("Correlation Heatmap")

    corr = df.corr(numeric_only=True)

    fig, ax = plt.subplots()
    cax = ax.matshow(corr)
    plt.xticks(range(len(corr.columns)), corr.columns, rotation=90)
    plt.yticks(range(len(corr.columns)), corr.columns)
    st.pyplot(fig)

    st.subheader("Steps vs Calories")

    fig, ax = plt.subplots()
    ax.scatter(df["Steps"], df["Calories"])
    ax.set_xlabel("Steps")
    ax.set_ylabel("Calories")
    st.pyplot(fig)

# ------------------------------------------------------------
# AI PREDICTION PAGE
# ------------------------------------------------------------
elif menu == "Prediction AI":

    st.subheader("Enter Your Activity Data")

    steps = st.slider("Steps", 1000, 20000, 7000)
    calories = st.slider("Calories Burned", 1000, 4000, 2200)
    heart = st.slider("Heart Rate", 50, 160, 80)
    sleep = st.slider("Sleep Hours", 3.0, 10.0, 7.0)
    bmi = st.slider("BMI", 15.0, 35.0, 23.0)

    X = df.drop("Fitness_Level", axis=1)
    y = df["Fitness_Level"]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    model = RandomForestClassifier(n_estimators=200)
    model.fit(X_train, y_train)

    user = pd.DataFrame({
        "Steps": [steps],
        "Calories": [calories],
        "Heart_Rate": [heart],
        "Sleep": [sleep],
        "BMI": [bmi]
    })

    prediction = model.predict(user)

    score = fitness_score(steps, sleep, bmi)

    st.success(f"Predicted Fitness Level: {prediction[0]}")
    st.info(f"Fitness Score: {score}/100")

# ------------------------------------------------------------
# HEALTH REPORT PAGE
# ------------------------------------------------------------
elif menu == "Health Report":

    st.subheader("AI Health Insights")

    st.write("Average Steps:", int(df["Steps"].mean()))
    st.write("Average Calories:", int(df["Calories"].mean()))
    st.write("Average Heart Rate:", int(df["Heart_Rate"].mean()))
    st.write("Average Sleep:", round(df["Sleep"].mean(), 2))

    st.subheader("Recommended Lifestyle Plan")

    st.write("• Walk at least 8,000–10,000 steps daily")
    st.write("• Maintain balanced nutrition")
    st.write("• Sleep 7–8 hours")
    st.write("• Exercise regularly")

st.markdown("---")
st.write("Developed by Sarthak Pal | AI + Data Science Project")

Overwriting app.py

In [67]:
!nohup streamlit run app.py &>/dev/null &
import time
time.sleep(3)
from pyngrok import ngrok

# --- IMPORTANT: Replace 'YOUR_NGROK_AUTH_TOKEN' with your actual ngrok authtoken ---
# The token should be just the string starting with '2_' or 'NgrokClient_'
ngrok.set_auth_token("3BTNKBMGYVFFIleYMxF4gJ784Pt_tmnY4wPCAerg9QCT3Chq")

public_url = ngrok.connect(addr='8501', proto='http')
print(f'Your Streamlit app is live at: {public_url}')

Your Streamlit app is live at: NgrokTunnel: "https://nonphrenetically-demagogic-rodolfo.ngrok-free.dev" -> "http://localhost:8501"

In [68]:
%%writefile app.py

# ============================================================
# FITNESS AI PLATFORM (PRODUCTION STYLE)
# Realistic Dataset + ML Pipeline + Better UI
# Developed by: Sarthak Pal
# ============================================================

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# ------------------------------------------------------------
# PAGE CONFIG
# ------------------------------------------------------------
st.set_page_config(
    page_title="Fitness AI Platform",
    page_icon="💚",
    layout="wide"
)

# ------------------------------------------------------------
# GREEN FITNESS UI
# ------------------------------------------------------------
st.markdown("""
<style>
.main-title {
    font-size:40px;
    font-weight:700;
    color:#22c55e;
}
.block-container {
    padding-top: 2rem;
}
.metric-card {
    background: linear-gradient(135deg,#16a34a,#22c55e);
    padding:20px;
    border-radius:12px;
    text-align:center;
    color:white;
}
</style>
""", unsafe_allow_html=True)

st.markdown('<p class="main-title">💚 Fitness AI Intelligence Platform</p>', unsafe_allow_html=True)

# ------------------------------------------------------------
# REALISTIC DATASET GENERATION
# ------------------------------------------------------------
@st.cache_data
def generate_dataset(n=2000):

    np.random.seed(42)

    steps = np.random.normal(8000, 3000, n).clip(1000, 20000)
    sleep = np.random.normal(7, 1.5, n).clip(3, 10)
    heart = np.random.normal(80, 15, n).clip(50, 160)
    bmi = np.random.normal(24, 4, n).clip(16, 38)

    calories = steps * 0.04 + np.random.normal(1800, 200, n)

    df = pd.DataFrame({
        "Steps": steps.astype(int),
        "Sleep": sleep,
        "Heart_Rate": heart,
        "BMI": bmi,
        "Calories": calories.astype(int)
    })

    # Health scoring logic
    score = (
        (df["Steps"] / 12000) * 40 +
        (df["Sleep"] / 8) * 30 +
        ((25 - abs(df["BMI"] - 22)) / 25) * 30
    )

    conditions = [
        score < 40,
        score < 60,
        score < 80,
        score >= 80
    ]

    labels = [
        "High Risk",
        "Needs Improvement",
        "Healthy",
        "Athlete Level"
    ]

    df["Fitness_Level"] = np.select(conditions, labels)

    return df

df = generate_dataset()

# ------------------------------------------------------------
# ML MODEL (TRAINED ONCE)
# ------------------------------------------------------------
@st.cache_resource
def train_model(data):

    X = data.drop("Fitness_Level", axis=1)
    y = data["Fitness_Level"]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    pipeline = Pipeline([
        ("scaler", StandardScaler()),
        ("model", RandomForestClassifier(
            n_estimators=300,
            max_depth=10,
            random_state=42
        ))
    ])

    pipeline.fit(X_train, y_train)

    preds = pipeline.predict(X_test)
    acc = accuracy_score(y_test, preds)

    return pipeline, acc

model, accuracy = train_model(df)

# ------------------------------------------------------------
# SIDEBAR
# ------------------------------------------------------------
st.sidebar.title("Navigation")

page = st.sidebar.radio(
    "Go to",
    ["Dashboard", "Analytics", "AI Prediction"]
)

# ------------------------------------------------------------
# DASHBOARD
# ------------------------------------------------------------
if page == "Dashboard":

    col1, col2, col3, col4 = st.columns(4)

    col1.metric("Users", len(df))
    col2.metric("Avg Steps", int(df["Steps"].mean()))
    col3.metric("Avg Sleep", round(df["Sleep"].mean(), 2))
    col4.metric("Model Accuracy", f"{round(accuracy*100,2)}%")

    st.subheader("Fitness Level Distribution")

    fig, ax = plt.subplots()
    df["Fitness_Level"].value_counts().plot(kind="bar", ax=ax)
    st.pyplot(fig)

# ------------------------------------------------------------
# ANALYTICS
# ------------------------------------------------------------
elif page == "Analytics":

    st.subheader("Dataset Preview")
    st.dataframe(df.head(50))

    st.subheader("Steps vs BMI")

    fig, ax = plt.subplots()
    ax.scatter(df["Steps"], df["BMI"], alpha=0.4)
    ax.set_xlabel("Steps")
    ax.set_ylabel("BMI")
    st.pyplot(fig)

    st.subheader("Correlation")

    corr = df.corr(numeric_only=True)

    fig, ax = plt.subplots()
    cax = ax.matshow(corr)
    plt.xticks(range(len(corr.columns)), corr.columns, rotation=90)
    plt.yticks(range(len(corr.columns)), corr.columns)
    st.pyplot(fig)

# ------------------------------------------------------------
# AI PREDICTION
# ------------------------------------------------------------
elif page == "AI Prediction":

    st.subheader("Enter Your Data")

    steps = st.slider("Daily Steps", 1000, 20000, 8000)
    sleep = st.slider("Sleep Hours", 3.0, 10.0, 7.0)
    heart = st.slider("Heart Rate", 50, 160, 80)
    bmi = st.slider("BMI", 15.0, 40.0, 23.0)
    calories = st.slider("Calories Burned", 1200, 4500, 2200)

    user = pd.DataFrame({
        "Steps": [steps],
        "Sleep": [sleep],
        "Heart_Rate": [heart],
        "BMI": [bmi],
        "Calories": [calories]
    })

    prediction = model.predict(user)[0]

    st.success(f"Your Fitness Status: {prediction}")

    # Score system
    score = int(
        (steps/12000)*40 +
        (sleep/8)*30 +
        ((25-abs(bmi-22))/25)*30
    )

    score = max(0, min(score, 100))

    st.progress(score/100)
    st.write(f"Fitness Score: {score}/100")

st.markdown("---")
st.write("Fitness AI Platform | Built by Sarthak Pal")

Overwriting app.py

This script creates a **Fitness Activity AI Dashboard** using Streamlit, a Python framework for building interactive web applications. It uses machine learning to predict fitness levels based on user input and provides personalized recommendations.

### 1. Imports and Page Configuration

- **`import streamlit as st`**: Imports the Streamlit library for creating the web app.
- **`import pandas as pd`, `import numpy as np`, `import matplotlib.pyplot as plt`**: Imports libraries for data manipulation, numerical operations, and plotting.
- **`from sklearn.ensemble import RandomForestClassifier`, `from sklearn.model_selection import train_test_split`, `from sklearn.metrics import accuracy_score`**: Imports scikit-learn modules for the machine learning model.
- **`st.set_page_config(...)`**: Configures the Streamlit page, setting the title, icon, and layout to `wide` for better display.

### 2. Custom UI Styling

- **`st.markdown("""<style>...</style>""", unsafe_allow_html=True)`**: Applies custom CSS styling to the Streamlit app to enhance its appearance, defining classes like `big-title` and `card` for consistent look and feel.
- **`st.markdown('<p class="big-title">...</p>', unsafe_allow_html=True)`**: Displays the main title of the dashboard using the custom `big-title` style.

### 3. Dataset Generation (`load_data` function)

- **`@st.cache_data`**: This decorator caches the function's output, so the data is loaded only once, improving performance.
- The `load_data` function generates a synthetic dataset with columns like `Steps`, `Calories`, `Heart_Rate`, `Sleep`, and `BMI`.
- It then categorizes each record into a `Fitness_Level` (e.g., 'Underactive', 'Moderate', 'Healthy', 'Highly Active') based on the `Steps` count using `np.select`. It includes a `default='Unknown'` to handle any cases not covered by the conditions and prevent `TypeError`.

### 4. Sidebar Navigation

- **`st.sidebar.title("Dashboard Menu")`**: Creates a title for the sidebar.
- **`menu = st.sidebar.radio(...)`**: Creates a radio button menu in the sidebar, allowing the user to navigate between different sections of the dashboard: 'Dashboard', 'Data Analysis', 'Fitness Prediction', and 'Health Report'.

### 5. Dashboard Section

- This section is displayed when 'Dashboard' is selected in the sidebar.
- It provides an overview of the fitness data with metrics like total users, average steps, calories, and sleep hours.
- It includes histograms for 'Daily Steps Distribution' and 'Calories Burned' to show data distributions.
- A bar chart displays the 'Fitness Category Distribution', showing the count of individuals in each fitness level.

### 6. Data Analysis Section

- This section is displayed when 'Data Analysis' is selected.
- **`st.dataframe(df)`**: Shows a preview of the generated dataset.
- **`df.corr(numeric_only=True)`**: Calculates the correlation matrix for numerical columns.
- A heatmap (`ax.matshow`) visualizes the correlation matrix, helping to understand relationships between different fitness metrics.

### 7. Fitness Prediction Section (Machine Learning)

- This section is for making predictions based on user input.
- **Sliders**: Allow the user to input their daily activity data (Steps, Calories Burned, Heart Rate, Sleep Hours, BMI).
- **Model Training**: A `RandomForestClassifier` is trained on the synthetic dataset to predict `Fitness_Level`.
- **User Prediction**: The trained model uses the user's input to predict their `Fitness_Level`.
- **`st.success(...)`**: Displays the predicted fitness level to the user.

### 8. Health Report Section

- This section provides general health insights and recommendations.
- It displays average values for various metrics from the dataset.
- It offers a list of general recommendations for maintaining a healthy lifestyle.

### 9. Footer

- **`st.markdown("---")` and `st.write(...)`**: Adds a horizontal separator and a developer credit at the bottom of the page.

In [69]:
!nohup streamlit run app.py &>/dev/null &
import time
time.sleep(3)
from pyngrok import ngrok

# The token should be just the string starting with '2_' or 'NgrokClient_'
ngrok.set_auth_token("3BTNKBMGYVFFIleYMxF4gJ784Pt_tmnY4wPCAerg9QCT3Chq")

public_url = ngrok.connect(addr='8501', proto='http')
print(f'Your Streamlit app is live at: {public_url}')

Your Streamlit app is live at: NgrokTunnel: "https://nonphrenetically-demagogic-rodolfo.ngrok-free.dev" -> "http://localhost:8501"

In [83]:
# Kill any existing Streamlit processes
!killall streamlit || true

# Restart Streamlit app in the background
!nohup streamlit run app.py &>/dev/null &

In [84]:
import time
from pyngrok import ngrok

time.sleep(5) # Give Streamlit a moment to start

# Terminate existing ngrok tunnels if any
ngrok.kill()

# Your ngrok auth token (replace if it's not already set in the environment or secrets)
# The token should be just the string starting with '2_' or 'NgrokClient_'
ngrok.set_auth_token("3BTNKBMGYVFFIleYMxF4gJ784Pt_tmnY4wPCAerg9QCT3Chq")

# Connect ngrok to the Streamlit port
public_url = ngrok.connect(addr='8501', proto='http')
print(f'Your Streamlit app is live at: {public_url}')

WARNING:pyngrok.process.ngrok:t=2026-03-27T09:58:47+0000 lvl=warn msg="failed to open private leg" id=7e640681aca7 privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"
WARNING:pyngrok.process.ngrok:t=2026-03-27T09:58:47+0000 lvl=warn msg="failed to open private leg" id=6dfccf50630f privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"

Your Streamlit app is live at: NgrokTunnel: "https://nonphrenetically-demagogic-rodolfo.ngrok-free.dev" -> "http://localhost:8501"

In [81]:
# ============================================================
# DIET RECOMMENDATION SYSTEM
# ============================================================

def generate_diet_plan(fitness_level, bmi, steps, workout):

    diet = {}

    # Base calorie estimation
    base_calories = 1800

    if fitness_level == "Underactive":
        calories = base_calories - 200
    elif fitness_level == "Moderate":
        calories = base_calories
    elif fitness_level == "Healthy":
        calories = base_calories + 200
    else:
        calories = base_calories + 400

    # Adjust based on activity
    calories += int(steps / 2000) * 50
    calories += int(workout / 30) * 100

    # BMI adjustments
    if bmi > 27:
        goal = "Fat Loss"
        calories -= 300
    elif bmi < 19:
        goal = "Weight Gain"
        calories += 300
    else:
        goal = "Maintain Fitness"

    # ============================================================
# DIET RECOMMENDATION SYSTEM (BMI-BASED SMART DIET ENGINE)
# ============================================================

def generate_diet_plan(fitness_level, bmi, steps, workout):

    diet = {}

    # Base calorie estimation
    base_calories = 1800

    if fitness_level == "Underactive":
        calories = base_calories - 200
    elif fitness_level == "Moderate":
        calories = base_calories
    elif fitness_level == "Healthy":
        calories = base_calories + 200
    else:
        calories = base_calories + 400

    # Adjust calories based on activity
    calories += int(steps / 2000) * 50
    calories += int(workout / 30) * 100

    # =========================================================
    # BMI-BASED GOAL + DIET PLAN
    # =========================================================

    # UNDERWEIGHT
    if bmi < 18.5:
        goal = "Weight Gain"
        calories += 400

        breakfast = [
            "Peanut butter toast",
            "Banana smoothie",
            "Oatmeal with milk",
            "Boiled eggs / Paneer bhurji"
        ]

        lunch = [
            "Rice + dal",
            "Chicken / paneer curry",
            "Avocado or healthy fats",
            "Yogurt"
        ]

        snack = [
            "Protein shake",
            "Almonds & cashews",
            "Peanut chikki"
        ]

        dinner = [
            "Whole wheat roti",
            "Paneer / fish",
            "Vegetables",
            "Milk before sleep"
        ]

    # NORMAL BMI
    elif 18.5 <= bmi <= 24.9:
        goal = "Maintain Fitness"

        breakfast = [
            "Oatmeal with fruits",
            "Boiled eggs / Paneer",
            "Green tea",
            "Whole grain toast"
        ]

        lunch = [
            "Brown rice or roti",
            "Grilled chicken / dal",
            "Vegetables",
            "Salad"
        ]

        snack = [
            "Fruit bowl",
            "Nuts",
            "Protein shake"
        ]

        dinner = [
            "Light meal",
            "Soup + vegetables",
            "Tofu / paneer / fish"
        ]

    # OVERWEIGHT
    elif 25 <= bmi <= 29.9:
        goal = "Fat Loss"
        calories -= 300

        breakfast = [
            "Boiled eggs",
            "Black coffee / green tea",
            "Low carb oats",
            "Fruit (apple)"
        ]

        lunch = [
            "Grilled chicken / tofu",
            "Large salad bowl",
            "Low carb roti",
            "Vegetables"
        ]

        snack = [
            "Greek yogurt",
            "Handful almonds",
            "Protein shake"
        ]

        dinner = [
            "Vegetable soup",
            "Grilled paneer / chicken",
            "Steamed vegetables"
        ]

    # OBESE
    else:
        goal = "Aggressive Fat Loss"
        calories -= 500

        breakfast = [
            "Green smoothie",
            "Boiled eggs",
            "Chia seed pudding"
        ]

        lunch = [
            "Large salad",
            "Lean protein (fish/chicken/tofu)",
            "Vegetables"
        ]

        snack = [
            "Green tea",
            "Walnuts",
            "Low fat yogurt"
        ]

        dinner = [
            "Light soup",
            "Steamed vegetables",
            "Small protein portion"
        ]

    # =========================================================
    # FINAL DIET STRUCTURE
    # =========================================================

    diet["Goal"] = goal
    diet["Recommended Calories"] = int(calories)
    diet["Breakfast"] = breakfast
    diet["Lunch"] = lunch
    diet["Snack"] = snack
    diet["Dinner"] = dinner

    return diet

In [73]:
page = st.sidebar.radio(
    "Select Module",
    [
        "Executive Dashboard",
        "AI Prediction Engine",
        "Diet Planner AI",
        "Advanced Analytics",
        "Model Intelligence",
        "Health Report Generator"
    ]
)

2026-03-27 09:50:19.963 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:50:19.970 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:50:19.973 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:50:19.977 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:50:19.979 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:50:19.982 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:50:19.985 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [74]:
# ============================================================
# DIET PLANNER AI
# ============================================================

elif page == "Diet Planner AI":

    st.header("🥗 AI Diet Recommendation System")

    st.write("Personalized nutrition plan based on your fitness results")

    col1, col2 = st.columns(2)

    with col1:
        steps = st.slider("Daily Steps", 1000, 20000, 8000)
        bmi = st.slider("BMI", 15.0, 38.0, 23.0)

    with col2:
        workout = st.slider("Workout Minutes", 0, 180, 40)
        sleep = st.slider("Sleep Hours", 3.0, 10.0, 7.0)

    # Predict fitness level using model
    user = pd.DataFrame({
        "Steps": [steps],
        "Calories": [2500],
        "Heart_Rate": [80],
        "Sleep": [sleep],
        "BMI": [bmi],
        "Workout_Minutes": [workout],
        "Water_Intake": [2.5]
    })

    user = feature_engineering(user)

    fitness_level = model.predict(user)[0]

    st.success(f"Detected Fitness Level: {fitness_level}")

    diet = generate_diet_plan(fitness_level, bmi, steps, workout)

    st.subheader("Your Goal")
    st.info(diet["Goal"])

    st.subheader("Daily Calories Needed")
    st.metric("Calories", diet["Recommended Calories"])

    st.subheader("🍳 Breakfast")
    for item in diet["Breakfast"]:
        st.write("•", item)

    st.subheader("🍛 Lunch")
    for item in diet["Lunch"]:
        st.write("•", item)

    st.subheader("🥤 Snacks")
    for item in diet["Snack"]:
        st.write("•", item)

    st.subheader("🍲 Dinner")
    for item in diet["Dinner"]:
        st.write("•", item)

SyntaxError: invalid syntax (3474783800.py, line 5)

In [ ]:
# ============================================================
# DIET PLANNER AI
# ============================================================

elif page == "Diet Planner AI":

    st.header("🥗 AI Diet Recommendation System")

    st.write("Personalized nutrition plan based on your fitness results")

    col1, col2 = st.columns(2)

    with col1:
        steps = st.slider("Daily Steps", 1000, 20000, 8000)
        bmi = st.slider("BMI", 15.0, 38.0, 23.0)

    with col2:
        workout = st.slider("Workout Minutes", 0, 180, 40)
        sleep = st.slider("Sleep Hours", 3.0, 10.0, 7.0)

    # Predict fitness level using model
    user = pd.DataFrame({
        "Steps": [steps],
        "Calories": [2500],
        "Heart_Rate": [80],
        "Sleep": [sleep],
        "BMI": [bmi],
        "Workout_Minutes": [workout],
        "Water_Intake": [2.5]
    })

    user = feature_engineering(user)

    fitness_level = model.predict(user)[0]

    st.success(f"Detected Fitness Level: {fitness_level}")

    diet = generate_diet_plan(fitness_level, bmi, steps, workout)

    st.subheader("Your Goal")
    st.info(diet["Goal"])

    st.subheader("Daily Calories Needed")
    st.metric("Calories", diet["Recommended Calories"])

    st.subheader("🍳 Breakfast")
    for item in diet["Breakfast"]:
        st.write("•", item)

    st.subheader("🍛 Lunch")
    for item in diet["Lunch"]:
        st.write("•", item)

    st.subheader("🥤 Snacks")
    for item in diet["Snack"]:
        st.write("•", item)

    st.subheader("🍲 Dinner")
    for item in diet["Dinner"]:
        st.write("•", item)
h other and review everything

SyntaxError: invalid syntax (3474783800.py, line 5)

In [ ]:
# ============================================================
# DIET PLANNER AI
# ============================================================

elif page == "Diet Planner AI":

    st.header("🥗 AI Diet Recommendation System")

    st.write("Personalized nutrition plan based on your fitness results")

    col1, col2 = st.columns(2)

    with col1:
        steps = st.slider("Daily Steps", 1000, 20000, 8000)
        bmi = st.slider("BMI", 15.0, 38.0, 23.0)

    with col2:
        workout = st.slider("Workout Minutes", 0, 180, 40)
        sleep = st.slider("Sleep Hours", 3.0, 10.0, 7.0)

    # Predict fitness level using model
    user = pd.DataFrame({
        "Steps": [steps],
        "Calories": [2500],
        "Heart_Rate": [80],
        "Sleep": [sleep],
        "BMI": [bmi],
        "Workout_Minutes": [workout],
        "Water_Intake": [2.5]
    })

    user = feature_engineering(user)

    fitness_level = model.predict(user)[0]

    st.success(f"Detected Fitness Level: {fitness_level}")

    diet = generate_diet_plan(fitness_level, bmi, steps, workout)

    st.subheader("Your Goal")
    st.info(diet["Goal"])

    st.subheader("Daily Calories Needed")
    st.metric("Calories", diet["Recommended Calories"])

    st.subheader("🍳 Breakfast")
    for item in diet["Breakfast"]:
        st.write("•", item)

    st.subheader("🍛 Lunch")
    for item in diet["Lunch"]:
        st.write("•", item)

    st.subheader("🥤 Snacks")
    for item in diet["Snack"]:
        st.write("•", item)

    st.subheader("🍲 Dinner")
    for item in diet["Dinner"]:
        st.write("•", item)
h other and review everything

SyntaxError: invalid syntax (3474783800.py, line 5)

In [ ]:
# ============================================================
# DIET PLANNER AI
# ============================================================

elif page == "Diet Planner AI":

    st.header("🥗 AI Diet Recommendation System")

    st.write("Personalized nutrition plan based on your fitness results")

    col1, col2 = st.columns(2)

    with col1:
        steps = st.slider("Daily Steps", 1000, 20000, 8000)
        bmi = st.slider("BMI", 15.0, 38.0, 23.0)

    with col2:
        workout = st.slider("Workout Minutes", 0, 180, 40)
        sleep = st.slider("Sleep Hours", 3.0, 10.0, 7.0)

    # Predict fitness level using model
    user = pd.DataFrame({
        "Steps": [steps],
        "Calories": [2500],
        "Heart_Rate": [80],
        "Sleep": [sleep],
        "BMI": [bmi],
        "Workout_Minutes": [workout],
        "Water_Intake": [2.5]
    })

    user = feature_engineering(user)

    fitness_level = model.predict(user)[0]

    st.success(f"Detected Fitness Level: {fitness_level}")

    diet = generate_diet_plan(fitness_level, bmi, steps, workout)

    st.subheader("Your Goal")
    st.info(diet["Goal"])

    st.subheader("Daily Calories Needed")
    st.metric("Calories", diet["Recommended Calories"])

    st.subheader("🍳 Breakfast")
    for item in diet["Breakfast"]:
        st.write("•", item)

    st.subheader("🍛 Lunch")
    for item in diet["Lunch"]:
        st.write("•", item)

    st.subheader("🥤 Snacks")
    for item in diet["Snack"]:
        st.write("•", item)

    st.subheader("🍲 Dinner")
    for item in diet["Dinner"]:
        st.write("•", item)
h other and review everything

SyntaxError: invalid syntax (3474783800.py, line 5)

In [ ]:
# ============================================================
# DIET PLANNER AI
# ============================================================

elif page == "Diet Planner AI":

    st.header("🥗 AI Diet Recommendation System")

    st.write("Personalized nutrition plan based on your fitness results")

    col1, col2 = st.columns(2)

    with col1:
        steps = st.slider("Daily Steps", 1000, 20000, 8000)
        bmi = st.slider("BMI", 15.0, 38.0, 23.0)

    with col2:
        workout = st.slider("Workout Minutes", 0, 180, 40)
        sleep = st.slider("Sleep Hours", 3.0, 10.0, 7.0)

    # Predict fitness level using model
    user = pd.DataFrame({
        "Steps": [steps],
        "Calories": [2500],
        "Heart_Rate": [80],
        "Sleep": [sleep],
        "BMI": [bmi],
        "Workout_Minutes": [workout],
        "Water_Intake": [2.5]
    })

    user = feature_engineering(user)

    fitness_level = model.predict(user)[0]

    st.success(f"Detected Fitness Level: {fitness_level}")

    diet = generate_diet_plan(fitness_level, bmi, steps, workout)

    st.subheader("Your Goal")
    st.info(diet["Goal"])

    st.subheader("Daily Calories Needed")
    st.metric("Calories", diet["Recommended Calories"])

    st.subheader("🍳 Breakfast")
    for item in diet["Breakfast"]:
        st.write("•", item)

    st.subheader("🍛 Lunch")
    for item in diet["Lunch"]:
        st.write("•", item)

    st.subheader("🥤 Snacks")
    for item in diet["Snack"]:
        st.write("•", item)

    st.subheader("🍲 Dinner")
    for item in diet["Dinner"]:
        st.write("•", item)
h other and review everything

SyntaxError: invalid syntax (3474783800.py, line 5)

In [ ]:
# ============================================================
# DIET PLANNER AI
# ============================================================

elif page == "Diet Planner AI":

    st.header("🥗 AI Diet Recommendation System")

    st.write("Personalized nutrition plan based on your fitness results")

    col1, col2 = st.columns(2)

    with col1:
        steps = st.slider("Daily Steps", 1000, 20000, 8000)
        bmi = st.slider("BMI", 15.0, 38.0, 23.0)

    with col2:
        workout = st.slider("Workout Minutes", 0, 180, 40)
        sleep = st.slider("Sleep Hours", 3.0, 10.0, 7.0)

    # Predict fitness level using model
    user = pd.DataFrame({
        "Steps": [steps],
        "Calories": [2500],
        "Heart_Rate": [80],
        "Sleep": [sleep],
        "BMI": [bmi],
        "Workout_Minutes": [workout],
        "Water_Intake": [2.5]
    })

    user = feature_engineering(user)

    fitness_level = model.predict(user)[0]

    st.success(f"Detected Fitness Level: {fitness_level}")

    diet = generate_diet_plan(fitness_level, bmi, steps, workout)

    st.subheader("Your Goal")
    st.info(diet["Goal"])

    st.subheader("Daily Calories Needed")
    st.metric("Calories", diet["Recommended Calories"])

    st.subheader("🍳 Breakfast")
    for item in diet["Breakfast"]:
        st.write("•", item)

    st.subheader("🍛 Lunch")
    for item in diet["Lunch"]:
        st.write("•", item)

    st.subheader("🥤 Snacks")
    for item in diet["Snack"]:
        st.write("•", item)

    st.subheader("🍲 Dinner")
    for item in diet["Dinner"]:
        st.write("•", item)
h other and review everything

SyntaxError: invalid syntax (3474783800.py, line 5)

In [75]:
# ============================================================
# DIET PLANNER AI
# ============================================================

elif page == "Diet Planner AI":

    st.header("🥗 AI Diet Recommendation System")

    st.write("Personalized nutrition plan based on your fitness results")

    col1, col2 = st.columns(2)

    with col1:
        steps = st.slider("Daily Steps", 1000, 20000, 8000)
        bmi = st.slider("BMI", 15.0, 38.0, 23.0)

    with col2:
        workout = st.slider("Workout Minutes", 0, 180, 40)
        sleep = st.slider("Sleep Hours", 3.0, 10.0, 7.0)

    # Predict fitness level using model
    user = pd.DataFrame({
        "Steps": [steps],
        "Calories": [2500],
        "Heart_Rate": [80],
        "Sleep": [sleep],
        "BMI": [bmi],
        "Workout_Minutes": [workout],
        "Water_Intake": [2.5]
    })

    user = feature_engineering(user)

    fitness_level = model.predict(user)[0]

    st.success(f"Detected Fitness Level: {fitness_level}")

    diet = generate_diet_plan(fitness_level, bmi, steps, workout)

    st.subheader("Your Goal")
    st.info(diet["Goal"])

    st.subheader("Daily Calories Needed")
    st.metric("Calories", diet["Recommended Calories"])

    st.subheader("🍳 Breakfast")
    for item in diet["Breakfast"]:
        st.write("•", item)

    st.subheader("🍛 Lunch")
    for item in diet["Lunch"]:
        st.write("•", item)

    st.subheader("🥤 Snacks")
    for item in diet["Snack"]:
        st.write("•", item)

    st.subheader("🍲 Dinner")
    for item in diet["Dinner"]:
        st.write("•", item)

SyntaxError: invalid syntax (2901195135.py, line 5)

In [76]:
import streamlit as st
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# Assuming load_data and generate_diet_plan are defined as in app.py
# and that df, model are available from app.py context

# --- Placeholder for df and model for isolated execution demonstration ---
# In the actual app.py, df and model are defined globally or via @st.cache_data / @st.cache_resource

# Re-create load_data to get df
@st.cache_data
def load_data_for_demo():
    np.random.seed(42)
    data = pd.DataFrame({
        "Steps": np.random.randint(2000, 15000, 500),
        "Calories": np.random.randint(1500, 3500, 500),
        "Heart_Rate": np.random.randint(60, 140, 500),
        "Sleep": np.random.uniform(4, 9, 500),
        "BMI": np.random.uniform(18, 32, 500)
    })
    conditions = [
        (data["Steps"] < 4000),
        (data["Steps"] < 8000),
        (data["Steps"] < 12000),
        (data["Steps"] >= 12000)
    ]
    labels = ["Underactive", "Moderate", "Healthy", "Highly Active"]
    data["Fitness_Level"] = np.select(conditions, labels, default='Unknown')
    return data

df_demo = load_data_for_demo()

# Re-create generate_diet_plan for isolated execution demonstration
def generate_diet_plan_for_demo(fitness_level, bmi, steps, workout):
    diet = {}
    base_calories = 1800
    if fitness_level == "Underactive":
        calories = base_calories - 200
    elif fitness_level == "Moderate":
        calories = base_calories
    elif fitness_level == "Healthy":
        calories = base_calories + 200
    else:
        calories = base_calories + 400
    calories += int(steps / 2000) * 50
    calories += int(workout / 30) * 100
    if bmi > 27:
        goal = "Fat Loss"
        calories -= 300
    elif bmi < 19:
        goal = "Weight Gain"
        calories += 300
    else:
        goal = "Maintain Fitness"
    diet["Goal"] = goal
    diet["Recommended Calories"] = calories
    diet["Breakfast"] = ["Oatmeal with fruits", "Boiled eggs / Paneer", "Green tea"]
    diet["Lunch"] = ["Brown rice or roti", "Grilled chicken / dal", "Vegetables", "Salad"]
    diet["Snack"] = ["Protein shake", "Nuts", "Banana"]
    diet["Dinner"] = ["Light meal", "Soup + vegetables", "Paneer / tofu / fish"]
    return diet

# Train a model for demo purposes
X_train_demo, X_test_demo, y_train_demo, y_test_demo = train_test_split(
    df_demo.drop("Fitness_Level", axis=1), df_demo["Fitness_Level"], test_size=0.2, random_state=42
)
model_demo = RandomForestClassifier()
model_demo.fit(X_train_demo, y_train_demo)



# Corrected 'Diet Planner AI' section (extracted from app.py)
# Note: In a live Streamlit app, 'menu' would be controlled by st.sidebar.radio
# and df/model would be globally available or cached.

# For demonstration, let's assume 'menu' is 'Diet Planner AI' for this block to be active.
# In a real Streamlit app, this would be within the main `if/elif` structure.

st.header("🥗 AI Diet Recommendation System")
st.write("Personalized nutrition plan based on your fitness results")

col1, col2 = st.columns(2)

with col1:
    steps_input = st.slider("Daily Steps", 1000, 20000, 8000, key="diet_steps_demo")
    bmi_input = st.slider("BMI", 15.0, 38.0, 23.0, key="diet_bmi_demo")

with col2:
    workout_input = st.slider("Workout Minutes", 0, 180, 40, key="diet_workout_demo")
    sleep_input = st.slider("Sleep Hours", 3.0, 10.0, 7.0, key="diet_sleep_demo")

user_for_prediction_demo = pd.DataFrame({
    "Steps": [steps_input],
    "Calories": [df_demo['Calories'].mean()],
    "Heart_Rate": [df_demo['Heart_Rate'].mean()],
    "Sleep": [sleep_input],
    "BMI": [bmi_input]
})

fitness_level_demo = model_demo.predict(user_for_prediction_demo)[0]

st.success(f"Detected Fitness Level: {fitness_level_demo}")

diet_demo = generate_diet_plan_for_demo(fitness_level_demo, bmi_input, steps_input, workout_input)

st.subheader("Your Goal")
st.info(diet_demo["Goal"])

st.subheader("Daily Calories Needed")
st.metric("Calories", diet_demo["Recommended Calories"])

st.subheader("🍳 Breakfast")
for item in diet_demo["Breakfast"]:
    st.write("•", item)

st.subheader("🍛 Lunch")
for item in diet_demo["Lunch"]:
    st.write("•", item)

st.subheader("🥤 Snacks")
for item in diet_demo["Snack"]:
    st.write("•", item)

st.subheader("🍲 Dinner")
for item in diet_demo["Dinner"]:
    st.write("•", item)

2026-03-27 09:52:11.134 No runtime found, using MemoryCacheStorageManager
2026-03-27 09:52:11.137 No runtime found, using MemoryCacheStorageManager
2026-03-27 09:52:11.141 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.356 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.357 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.358 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.360 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.363 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.365 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.366 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.367 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.368 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.371 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.372 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.374 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.376 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.377 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.379 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.381 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.382 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.383 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.384 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.384 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.385 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.385 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.387 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.387 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.388 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.389 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.391 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.391 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.392 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.393 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.394 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.394 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.395 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.412 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.413 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.414 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.415 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.416 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.417 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.418 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.419 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.420 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.421 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.422 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.423 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.424 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.425 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.426 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.426 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.427 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.428 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.429 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.430 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.431 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.432 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.433 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.433 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.434 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.434 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.435 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.436 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.436 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.437 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.439 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.439 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.440 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.441 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.441 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.442 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.443 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.444 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.445 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.446 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.446 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.447 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.448 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.449 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.449 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.450 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.452 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.452 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.453 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.454 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.454 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.455 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.456 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.456 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.457 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.459 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.459 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.460 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.461 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.461 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.462 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.463 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.463 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.464 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.465 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.466 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.467 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.469 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.469 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.470 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.470 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.471 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.472 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.472 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.473 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.475 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.476 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.476 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.477 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.478 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.478 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.479 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.480 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.480 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.481 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.483 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.484 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.484 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.485 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.486 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.487 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.488 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.488 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.489 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.490 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.490 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.491 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.492 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.493 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.493 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.495 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.496 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.496 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.497 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-27 09:52:11.498 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# Re-define the load_data function from app.py to generate the dataset
# This ensures the model is trained on the same data distribution as the app.
def load_data():
    np.random.seed(42)

    data = pd.DataFrame({
        "Steps": np.random.randint(2000, 15000, 500),
        "Calories": np.random.randint(1500, 3500, 500),
        "Heart_Rate": np.random.randint(60, 140, 500),
        "Sleep": np.random.uniform(4, 9, 500),
        "BMI": np.random.uniform(18, 32, 500)
    })

    conditions = [
        (data["Steps"] < 4000),
        (data["Steps"] < 8000),
        (data["Steps"] < 12000),
        (data["Steps"] >= 12000)
    ]

    labels = ["Underactive", "Moderate", "Healthy", "Highly Active"]
    data["Fitness_Level"] = np.select(conditions, labels, default='Unknown')

    return data

df = load_data()

# Train the model as done in app.py
X = df.drop("Fitness_Level", axis=1)
y = df["Fitness_Level"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestClassifier()
model.fit(X_train, y_train)

# Sample input data for prediction
sample_steps = 7500
sample_calories = 2500
sample_heart_rate = 75
sample_sleep = 7.5
sample_bmi = 24.0

user_input = pd.DataFrame({
    "Steps": [sample_steps],
    "Calories": [sample_calories],
    "Heart_Rate": [sample_heart_rate],
    "Sleep": [sample_sleep],
    "BMI": [sample_bmi]
})

# Make a prediction
predicted_fitness_level = model.predict(user_input)

print(f"Sample Input: Steps={sample_steps}, Calories={sample_calories}, Heart Rate={sample_heart_rate}, Sleep={sample_sleep}, BMI={sample_bmi}")
print(f"Predicted Fitness Level: {predicted_fitness_level[0]}")

In [ ]:
!netstat -tuln | grep 8501

In [ ]:
# ============================================================
# FITNESS ACTIVITY ANALYSIS USING MACHINE LEARNING
# Streamlit + ML Project
# By: Sarthak Pal
# ============================================================

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# ------------------------------------------------------------
# Page Configuration
# ------------------------------------------------------------
st.set_page_config(page_title="Fitness Activity Dashboard", layout="wide")

st.title("🏃 Fitness Activity Analysis using Machine Learning")
st.subheader("Metasatellite Health Intelligence System")

# ------------------------------------------------------------
# Create Built-in Dataset
# ------------------------------------------------------------
@st.cache_data
def load_data():
    np.random.seed(42)

    data = pd.DataFrame({
        "Steps": np.random.randint(2000, 15000, 300),
        "Calories_Burned": np.random.randint(1500, 3500, 300),
        "Heart_Rate": np.random.randint(60, 140, 300),
        "Sleep_Hours": np.random.uniform(4, 9, 300),
        "BMI": np.random.uniform(18, 32, 300)
    })

    # Fitness Level Logic
    conditions = [
        (data["Steps"] < 4000),
        (data["Steps"] >= 4000) & (data["Steps"] < 8000),
        (data["Steps"] >= 8000) & (data["Steps"] < 12000),
        (data["Steps"] >= 12000)
    ]

    labels = ["Underactive", "Moderate", "Healthy", "Highly Active"]

    data["Fitness_Level"] = np.select(conditions, labels, default='Unknown')

    return data


df = load_data()

# ------------------------------------------------------------
# Sidebar
# ------------------------------------------------------------
st.sidebar.header("Enter Your Daily Activity")

steps = st.sidebar.slider("Daily Steps", 1000, 20000, 6000)
calories = st.sidebar.slider("Calories Burned", 1000, 4000, 2200)
heart_rate = st.sidebar.slider("Heart Rate", 50, 160, 80)
sleep = st.sidebar.slider("Sleep Hours", 3.0, 10.0, 7.0)
bmi = st.sidebar.slider("BMI", 15.0, 35.0, 23.0)

user_data = pd.DataFrame({
    "Steps": [steps],
    "Calories_Burned": [calories],
    "Heart_Rate": [heart_rate],
    "Sleep_Hours": [sleep],
    "BMI": [bmi]
})

# ------------------------------------------------------------
# Dataset Preview
# ------------------------------------------------------------
st.subheader("Dataset Preview")
st.dataframe(df.head())

# ------------------------------------------------------------
# Basic Dataset Info
# ------------------------------------------------------------
st.subheader("Dataset Summary")

col1, col2, col3 = st.columns(3)

col1.metric("Total Records", len(df))
col2.metric("Average Steps", int(df["Steps"].mean()))
col3.metric("Average Sleep Hours", round(df["Sleep_Hours"].mean(), 2))

# ------------------------------------------------------------
# Exploratory Data Analysis
# ------------------------------------------------------------
st.subheader("Exploratory Data Analysis")

col1, col2 = st.columns(2)

with col1:
    fig1, ax1 = plt.subplots()
    ax1.hist(df["Steps"], bins=20)
    ax1.set_title("Steps Distribution")
    ax1.grid(True, linestyle='--', alpha=0.6)
    fig1.tight_layout()
    st.pyplot(fig1)

with col2:
    fig2, ax2 = plt.subplots()
    ax2.hist(df["Calories_Burned"], bins=20)
    ax2.set_title("Calories Burned Distribution")
    ax2.grid(True, linestyle='--', alpha=0.6)
    fig2.tight_layout()
    st.pyplot(fig2)

col3, col4 = st.columns(2)

with col3:
    fig3, ax3 = plt.subplots()
    ax3.scatter(df["Steps"], df["Calories_Burned"])
    ax3.set_xlabel("Steps")
    ax3.set_ylabel("Calories Burned")
    ax3.set_title("Steps vs Calories")
    ax3.grid(True, linestyle='--', alpha=0.6)
    fig3.tight_layout()
    st.pyplot(fig3)

with col4:
    fig4, ax4 = plt.subplots()
    ax4.hist(df["Sleep_Hours"], bins=20)
    ax4.set_title("Sleep Hours Distribution")
    ax4.grid(True, linestyle='--', alpha=0.6)
    fig4.tight_layout()
    st.pyplot(fig4)

# ------------------------------------------------------------
# Machine Learning Model
# ------------------------------------------------------------
st.subheader("Machine Learning Model Training")

X = df.drop("Fitness_Level", axis=1)
y = df["Fitness_Level"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestClassifier(n_estimators=200)
model.fit(X_train, y_train)

predictions = model.predict(X_test)
accuracy = accuracy_score(y_test, predictions)

st.success(f"Model Accuracy: {round(accuracy * 100, 2)} %")

# ------------------------------------------------------------
# Feature Importance
# ------------------------------------------------------------
st.subheader("Feature Importance")

importance = model.feature_importances_
features = X.columns

fig5, ax5 = plt.subplots()
ax5.barh(features, importance)
ax5.set_title("Feature Importance in Prediction")
fig5.tight_layout()
st.pyplot(fig5)

# ------------------------------------------------------------
# User Prediction
# ------------------------------------------------------------
st.subheader("Your Fitness Prediction")

prediction = model.predict(user_data)

st.success(f"Predicted Fitness Level: {prediction[0]}")

# ------------------------------------------------------------
# Recommendations
# ------------------------------------------------------------
st.subheader("Personalized Health Recommendations")

if prediction[0] == "Underactive":
    st.warning("You need more physical activity.")
    st.write("Recommended Plan:")
    st.write("• Walk 8,000–10,000 steps daily")
    st.write("• Start light cardio workouts")
    st.write("• Eat more protein and vegetables")

elif prediction[0] == "Moderate":
    st.info("You are moderately active.")
    st.write("Recommended Plan:")
    st.write("• Increase workouts to 4 days per week")
    st.write("• Maintain balanced diet")
    st.write("• Improve sleep quality")

elif prediction[0] == "Healthy":
    st.success("Great! You are maintaining a healthy lifestyle.")
    st.write("Recommended Plan:")
    st.write("• Continue regular workouts")
    st.write("• Add strength training")
    st.write("• Maintain nutrition balance")

elif prediction[0] == "Highly Active":
    st.success("Excellent fitness level!")
    st.write("Recommended Plan:")
    st.write("• Maintain workout consistency")
    st.write("• High protein diet")
    st.write("• Proper recovery and hydration")

# ------------------------------------------------------------
# Health Report
# ------------------------------------------------------------
st.subheader("Health Insight Report")

report = pd.DataFrame({
    "Metric": ["Steps", "Calories Burned", "Heart Rate", "Sleep Hours", "BMI"],
    "Your Value": [steps, calories, heart_rate, sleep, bmi]
})

st.table(report)

st.write("Overall Fitness Status:", prediction[0])

st.markdown("---")
st.write("Developed by **Sarthak Pal** | Data Science Project")

In [ ]:
%%writefile app.py
# ============================================================
# ULTIMATE FITNESS AI DASHBOARD
# Advanced UI + Machine Learning + Analytics
# Developed by: Sarthak Pal
# ============================================================

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# ------------------------------------------------------------
# Page Setup
# ------------------------------------------------------------
st.set_page_config(
    page_title="Fitness AI Dashboard",
    page_icon="🏃",
    layout="wide"
)

# ------------------------------------------------------------
# Modern UI Styling
# ------------------------------------------------------------
st.markdown("""
<style>
.main-title {
    font-size:45px;
    font-weight:800;
    color:#00F5A0;
}

.card {
    background: rgba(255,255,255,0.05);
    padding:20px;
    border-radius:15px;
    backdrop-filter: blur(10px);
    box-shadow:0 4px 20px rgba(0,0,0,0.2);
}

.metric {
    font-size:28px;
    font-weight:bold;
}

.sidebar .sidebar-content {
    background: linear-gradient(180deg,#0f2027,#203a43,#2c5364);
}
</style>
""", unsafe_allow_html=True)

st.markdown('<p class="main-title">🏋️ AI Fitness Intelligence Dashboard</p>', unsafe_allow_html=True)
st.write("Machine Learning Powered Health Insights System")

# ------------------------------------------------------------
# Dataset Generator
# ------------------------------------------------------------
@st.cache_data
def load_data():
    np.random.seed(42)

    data = pd.DataFrame({
        "Steps": np.random.randint(2000, 15000, 500),
        "Calories": np.random.randint(1500, 3500, 500),
        "Heart_Rate": np.random.randint(60, 140, 500),
        "Sleep": np.random.uniform(4, 9, 500),
        "BMI": np.random.uniform(18, 32, 500)
    })

    conditions = [
        (data["Steps"] < 4000),
        (data["Steps"] < 8000),
        (data["Steps"] < 12000),
        (data["Steps"] >= 12000)
    ]

    labels = ["Underactive", "Moderate", "Healthy", "Highly Active"]

    data["Fitness_Level"] = np.select(conditions, labels, default='Unknown')

    return data

df = load_data()

# ------------------------------------------------------------
# Sidebar Navigation
# ------------------------------------------------------------
st.sidebar.title("Navigation")

menu = st.sidebar.radio(
    "Select Page",
    ["Dashboard", "Analytics", "Prediction AI", "Health Report"]
)

# ------------------------------------------------------------
# Fitness Score Function
# ------------------------------------------------------------
def fitness_score(steps, sleep, bmi):
    score = 0

    if steps > 10000:
        score += 40
    elif steps > 7000:
        score += 30
    else:
        score += 15

    if sleep >= 7:
        score += 30
    else:
        score += 15

    if 18.5 <= bmi <= 24.9:
        score += 30
    else:
        score += 15

    return score

# ------------------------------------------------------------
# DASHBOARD PAGE
# ------------------------------------------------------------
if menu == "Dashboard":

    st.subheader("System Overview")

    col1, col2, col3, col4 = st.columns(4)

    col1.metric("Total Records", len(df))
    col2.metric("Average Steps", int(df["Steps"].mean()))
    col3.metric("Average Calories", int(df["Calories"].mean()))
    col4.metric("Average Sleep", round(df["Sleep"].mean(), 2))

    st.subheader("Fitness Category Distribution")

    fig, ax = plt.subplots()
    df["Fitness_Level"].value_counts().plot(kind="bar", ax=ax)
    st.pyplot(fig)

# ------------------------------------------------------------
# ANALYTICS PAGE
# ------------------------------------------------------------
elif menu == "Analytics":

    st.subheader("Dataset Overview")

    st.dataframe(df)

    st.subheader("Correlation Heatmap")

    corr = df.corr(numeric_only=True)

    fig, ax = plt.subplots()
    cax = ax.matshow(corr)
    plt.xticks(range(len(corr.columns)), corr.columns, rotation=90)
    plt.yticks(range(len(corr.columns)), corr.columns)
    st.pyplot(fig)

    st.subheader("Steps vs Calories")

    fig, ax = plt.subplots()
    ax.scatter(df["Steps"], df["Calories"])
    ax.set_xlabel("Steps")
    ax.set_ylabel("Calories")
    st.pyplot(fig)

# ------------------------------------------------------------
# AI PREDICTION PAGE
# ------------------------------------------------------------
elif menu == "Prediction AI":

    st.subheader("Enter Your Activity Data")

    steps = st.slider("Steps", 1000, 20000, 7000)
    calories = st.slider("Calories Burned", 1000, 4000, 2200)
    heart = st.slider("Heart Rate", 50, 160, 80)
    sleep = st.slider("Sleep Hours", 3.0, 10.0, 7.0)
    bmi = st.slider("BMI", 15.0, 35.0, 23.0)

    X = df.drop("Fitness_Level", axis=1)
    y = df["Fitness_Level"]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    model = RandomForestClassifier(n_estimators=200)
    model.fit(X_train, y_train)

    user = pd.DataFrame({
        "Steps": [steps],
        "Calories": [calories],
        "Heart_Rate": [heart],
        "Sleep": [sleep],
        "BMI": [bmi]
    })

    prediction = model.predict(user)

    score = fitness_score(steps, sleep, bmi)

    st.success(f"Predicted Fitness Level: {prediction[0]}")
    st.info(f"Fitness Score: {score}/100")

# ------------------------------------------------------------
# HEALTH REPORT PAGE
# ------------------------------------------------------------
elif menu == "Health Report":

    st.subheader("AI Health Insights")

    st.write("Average Steps:", int(df["Steps"].mean()))
    st.write("Average Calories:", int(df["Calories"].mean()))
    st.write("Average Heart Rate:", int(df["Heart_Rate"].mean()))
    st.write("Average Sleep:", round(df["Sleep"].mean(), 2))

    st.subheader("Recommended Lifestyle Plan")

    st.write("• Walk at least 8,000–10,000 steps daily")
    st.write("• Maintain balanced nutrition")
    st.write("• Sleep 7–8 hours")
    st.write("• Exercise regularly")

st.markdown("---")
st.write("Developed by Sarthak Pal | AI + Data Science Project")

In [ ]:
# ============================================================
# FITNESS ACTIVITY ANALYSIS DASHBOARD (ADVANCED UI)
# Modern Streamlit Dashboard
# ============================================================

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# ------------------------------------------------------------
# Page Configuration
# ------------------------------------------------------------
st.set_page_config(
    page_title="Fitness AI Dashboard",
    page_icon="🏋️",
    layout="wide"
)

# ------------------------------------------------------------
# Custom UI Styling
# ------------------------------------------------------------
st.markdown("""
<style>
.big-title {
    font-size:40px;
    font-weight:bold;
    color:#00C2FF;
}
.card {
    padding:20px;
    border-radius:15px;
    background-color:#111111;
    color:white;
    box-shadow:0px 4px 10px rgba(0,0,0,0.3);
}
.metric {
    font-size:25px;
    font-weight:bold;
}
</style>
""", unsafe_allow_html=True)

st.markdown('<p class="big-title">🏃 Fitness Activity AI Dashboard</p>', unsafe_allow_html=True)
st.write("Machine Learning Powered Health Insights")

# ------------------------------------------------------------
# Dataset
# ------------------------------------------------------------
@st.cache_data
def load_data():
    np.random.seed(42)
    data = pd.DataFrame({
        "Steps": np.random.randint(2000, 15000, 400),
        "Calories": np.random.randint(1500, 3500, 400),
        "Heart_Rate": np.random.randint(60, 140, 400),
        "Sleep": np.random.uniform(4, 9, 400),
        "BMI": np.random.uniform(18, 32, 400)
    })

    conditions = [
        (data["Steps"] < 4000),
        (data["Steps"] < 8000),
        (data["Steps"] < 12000),
        (data["Steps"] >= 12000)
    ]

    labels = ["Underactive", "Moderate", "Healthy", "Highly Active"]
    data["Fitness_Level"] = np.select(conditions, labels, default='Unknown')

    return data

df = load_data()

# ------------------------------------------------------------
# Sidebar Navigation
# ------------------------------------------------------------
st.sidebar.title("Dashboard Menu")

menu = st.sidebar.radio(
    "Navigate",
    ["Dashboard", "Data Analysis", "Fitness Prediction", "Health Report"]
)

# ------------------------------------------------------------
# DASHBOARD
# ------------------------------------------------------------
if menu == "Dashboard":

    st.subheader("Fitness Overview")

    col1, col2, col3, col4 = st.columns(4)

    col1.metric("Users", len(df))
    col2.metric("Avg Steps", int(df["Steps"].mean()))
    col3.metric("Avg Calories", int(df["Calories"].mean()))
    col4.metric("Avg Sleep", round(df["Sleep"].mean(), 2))

    st.subheader("Activity Trends")

    col1, col2 = st.columns(2)

    with col1:
        fig, ax = plt.subplots()
        ax.hist(df["Steps"], bins=25)
        ax.set_title("Daily Steps Distribution")
        st.pyplot(fig)

    with col2:
        fig, ax = plt.subplots()
        ax.hist(df["Calories"], bins=25)
        ax.set_title("Calories Burned")
        st.pyplot(fig)

    st.subheader("Fitness Category Distribution")

    fig, ax = plt.subplots()
    df["Fitness_Level"].value_counts().plot(kind="bar", ax=ax)
    st.pyplot(fig)

# ------------------------------------------------------------
# DATA ANALYSIS
# ------------------------------------------------------------
elif menu == "Data Analysis":

    st.subheader("Dataset")

    st.dataframe(df)

    st.subheader("Correlation Analysis")

    corr = df.corr(numeric_only=True)

    fig, ax = plt.subplots()
    cax = ax.matshow(corr)
    plt.xticks(range(len(corr.columns)), corr.columns, rotation=90)
    plt.yticks(range(len(corr.columns)), corr.columns)
    st.pyplot(fig)

# ------------------------------------------------------------
# MACHINE LEARNING
# ------------------------------------------------------------
elif menu == "Fitness Prediction":

    st.subheader("Enter Your Daily Activity")

    steps = st.slider("Steps", 1000, 20000, 7000)
    calories = st.slider("Calories Burned", 1000, 4000, 2200)
    heart = st.slider("Heart Rate", 50, 160, 80)
    sleep = st.slider("Sleep Hours", 3.0, 10.0, 7.0)
    bmi = st.slider("BMI", 15.0, 35.0, 23.0)

    X = df.drop("Fitness_Level", axis=1)
    y = df["Fitness_Level"]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    model = RandomForestClassifier()
    model.fit(X_train, y_train)

    user = pd.DataFrame({
        "Steps": [steps],
        "Calories": [calories],
        "Heart_Rate": [heart],
        "Sleep": [sleep],
        "BMI": [bmi]
    })

    prediction = model.predict(user)

    st.success(f"Your Fitness Level: {prediction[0]}")

# ------------------------------------------------------------
# HEALTH REPORT
# ------------------------------------------------------------
elif menu == "Health Report":

    st.subheader("Generated Health Insights")

    st.write("This report summarizes the user's fitness performance.")

    st.write("Average Steps:", int(df["Steps"].mean()))
    st.write("Average Calories:", int(df["Calories"].mean()))
    st.write("Average Heart Rate:", int(df["Heart_Rate"].mean()))
    st.write("Average Sleep Hours:", round(df["Sleep"].mean(), 2))

    st.subheader("Recommendations")

    st.write("• Maintain regular exercise")
    st.write("• Sleep 7–8 hours daily")
    st.write("• Balanced diet")
    st.write("• Track your activity daily")

st.markdown("---")
st.write("Developed by Sarthak Pal | Machine Learning Project")

In [82]:
%%writefile app.py
# ============================================================
# FITNESS AI DASHBOARD (GREEN FITNESS THEME)
# Modern UI + Clean Layout
# ============================================================

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# ------------------------------------------------------------
# PAGE SETTINGS
# ------------------------------------------------------------
st.set_page_config(
    page_title="Fitness AI Dashboard",
    page_icon="💚",
    layout="wide"
)

# ------------------------------------------------------------
# GREEN FITNESS UI STYLE
# ------------------------------------------------------------
st.markdown("""
<style>

body {
    background-color: #0f172a;
}

.main-title {
    font-size:42px;
    font-weight:700;
    color:#22c55e;
}

.card {
    background: #111827;
    padding:20px;
    border-radius:14px;
    border:1px solid #1f2937;
}

.metric-card {
    background: linear-gradient(135deg,#14532d,#22c55e);
    padding:20px;
    border-radius:14px;
    color:white;
    text-align:center;
}

.section {
    margin-top:20px;
}

</style>
""", unsafe_allow_html=True)

st.markdown('<p class="main-title">💚 Fitness Intelligence Dashboard</p>', unsafe_allow_html=True)
st.write("AI Powered Activity Analysis System")

# ------------------------------------------------------------
# DATASET
# ------------------------------------------------------------
@st.cache_data
def load_data():
    np.random.seed(42)

    data = pd.DataFrame({
        "Steps": np.random.randint(2000, 15000, 500),
        "Calories": np.random.randint(1500, 3500, 500),
        "Heart_Rate": np.random.randint(60, 140, 500),
        "Sleep": np.random.uniform(4, 9, 500),
        "BMI": np.random.uniform(18, 32, 500)
    })

    conditions = [
        (data["Steps"] < 4000),
        (data["Steps"] < 8000),
        (data["Steps"] < 12000),
        (data["Steps"] >= 12000)
    ]

    labels = ["Underactive", "Moderate", "Healthy", "Highly Active"]
    data["Fitness_Level"] = np.select(conditions, labels, default='Unknown')

    return data

df = load_data()

# ------------------------------------------------------------
# ML MODEL (TRAINED ONCE)
# ------------------------------------------------------------
@st.cache_resource
def train_model(data):
    X = data.drop("Fitness_Level", axis=1)
    y = data["Fitness_Level"]
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )
    model = RandomForestClassifier()
    model.fit(X_train, y_train)
    return model

model = train_model(df)

# ------------------------------------------------------------
# DIET RECOMMENDATION SYSTEM
# ------------------------------------------------------------
def generate_diet_plan(fitness_level, bmi, steps, workout):

    diet = {}

    # Base calorie estimation
    base_calories = 1800

    if fitness_level == "Underactive":
        calories = base_calories - 200
    elif fitness_level == "Moderate":
        calories = base_calories
    else:
        calories = base_calories + 400

    # Adjust based on activity
    calories += int(steps / 2000) * 50
    calories += int(workout / 30) * 100

    # BMI adjustments
    if bmi > 27:
        goal = "Fat Loss"
        calories -= 300
    elif bmi < 19:
        goal = "Weight Gain"
        calories += 300
    else:
        goal = "Maintain Fitness"

    # Diet Plan
    diet["Goal"] = goal
    diet["Recommended Calories"] = calories

    diet["Breakfast"] = [
        "Oatmeal with fruits",
        "Boiled eggs / Paneer",
        "Green tea"
    ]

    diet["Lunch"] = [
        "Brown rice or roti",
        "Grilled chicken / dal",
        "Vegetables",
        "Salad"
    ]

    diet["Snack"] = [
        "Protein shake",
        "Nuts",
        "Banana"
    ]

    diet["Dinner"] = [
        "Light meal",
        "Soup + vegetables",
        "Paneer / tofu / fish"
    ]

    return diet

# ============================================================
# ADVANCED FITNESS INTELLIGENCE MODULE
# ============================================================

class FitnessAI:

    def __init__(self):
        pass

    # --------------------------------------------------------
    # BMR Calculator
    # --------------------------------------------------------
    def calculate_bmr(self, weight, height, age, gender):

        if gender == "Male":
            bmr = 10 * weight + 6.25 * height - 5 * age + 5
        else:
            bmr = 10 * weight + 6.25 * height - 5 * age - 161

        return int(bmr)

    # --------------------------------------------------------
    # Daily Calories
    # --------------------------------------------------------
    def daily_calories(self, bmr, activity_level):

        activity_multiplier = {
            "Low": 1.2,
            "Moderate": 1.5,
            "High": 1.75
        }

        return int(bmr * activity_multiplier[activity_level])

    # --------------------------------------------------------
    # Macro Calculation
    # --------------------------------------------------------
    def macros(self, calories, goal):

        if goal == "Fat Loss":
            protein = calories * 0.40 / 4
            carbs = calories * 0.30 / 4
            fats = calories * 0.30 / 9

        elif goal == "Muscle Gain":
            protein = calories * 0.35 / 4
            carbs = calories * 0.45 / 4
            fats = calories * 0.20 / 9

        else:
            protein = calories * 0.30 / 4
            carbs = calories * 0.40 / 4
            fats = calories * 0.30 / 9

        return {
            "Protein (g)": int(protein),
            "Carbs (g)": int(carbs),
            "Fats (g)": int(fats)
        }

    # --------------------------------------------------------
    # Weekly Diet Plan
    # --------------------------------------------------------
    def weekly_diet(self):

        plan = {
            "Monday": "High Protein Meals",
            "Tuesday": "Balanced Diet",
            "Wednesday": "Low Carb Focus",
            "Thursday": "Muscle Recovery Meals",
            "Friday": "Protein Rich Diet",
            "Saturday": "Athlete Level Nutrition",
            "Sunday": "Light Detox Diet"
        }

        return plan

    # --------------------------------------------------------
    # AI Coach Advice
    # --------------------------------------------------------
    def ai_coach(self, fitness_level, sleep, steps):

        if fitness_level == "Underactive":
            return "Start walking daily and build consistency."

        if sleep < 6:
            return "Improve sleep for better recovery."

        if steps > 12000:
            return "Great work! Focus on recovery and hydration."

        return "Maintain balanced lifestyle."

# ------------------------------------------------------------
# SIDEBAR
# ------------------------------------------------------------
st.sidebar.title("Fitness Menu")

menu = st.sidebar.radio(
    "Navigation",
    ["Dashboard", "Analytics", "AI Prediction", "Diet Planner AI", "Advanced Diet System"]
)

# ------------------------------------------------------------
# DASHBOARD
# ------------------------------------------------------------
if menu == "Dashboard":

    st.subheader("Overview")

    col1, col2, col3, col4 = st.columns(4)

    col1.markdown(f"""
    <div class="metric-card">
    <h3>Total Users</h3>
    <h2>{len(df)}</h2>
    </div>
    """, unsafe_allow_html=True)

    col2.markdown(f"""
    <div class="metric-card">
    <h3>Avg Steps</h3>
    <h2>{int(df['Steps'].mean())}</h2>
    </div>
    """, unsafe_allow_html=True)

    col3.markdown(f"""
    <div class="metric-card">
    <h3>Avg Calories</h3>
    <h2>{int(df['Calories'].mean())}</h2>
    </div>
    """, unsafe_allow_html=True)

    col4.markdown(f"""
    <div class="metric-card">
    <h3>Avg Sleep</h3>
    <h2>{round(df['Sleep'].mean(),2)}</h2>
    </div>
    """, unsafe_allow_html=True)

    st.markdown("---")

    col1, col2 = st.columns(2)

    with col1:
        fig, ax = plt.subplots()
        ax.hist(df["Steps"], bins=25)
        ax.set_title("Steps Distribution")
        st.pyplot(fig)

    with col2:
        fig, ax = plt.subplots()
        ax.hist(df["Calories"], bins=25)
        ax.set_title("Calories Burned")
        st.pyplot(fig)

# ------------------------------------------------------------
# ANALYTICS
# ------------------------------------------------------------
elif menu == "Analytics":

    st.subheader("Dataset")

    st.dataframe(df)

    st.subheader("Correlation")

    corr = df.corr(numeric_only=True)

    fig, ax = plt.subplots()
    cax = ax.matshow(corr)
    plt.xticks(range(len(corr.columns)), corr.columns, rotation=90)
    plt.yticks(range(len(corr.columns)), corr.columns)
    st.pyplot(fig)

# ------------------------------------------------------------
# AI PREDICTION
# ------------------------------------------------------------
elif menu == "AI Prediction":

    st.subheader("Enter Your Activity Data")

    steps = st.slider("Steps", 1000, 20000, 8000)
    calories = st.slider("Calories", 1000, 4000, 2200)
    heart = st.slider("Heart Rate", 50, 160, 80)
    sleep = st.slider("Sleep Hours", 3.0, 10.0, 7.0)
    bmi = st.slider("BMI", 15.0, 35.0, 23.0)

    user = pd.DataFrame({
        "Steps": [steps],
        "Calories": [calories],
        "Heart_Rate": [heart],
        "Sleep": [sleep],
        "BMI": [bmi]
    })

    prediction = model.predict(user)

    st.success(f"Your Fitness Level: {prediction[0]}")

# ------------------------------------------------------------
# DIET PLANNER AI
# ------------------------------------------------------------
elif menu == "Diet Planner AI":

    st.header("🥗 AI Diet Recommendation System")

    st.write("Personalized nutrition plan based on your fitness results")

    col1, col2 = st.columns(2)

    with col1:
        steps_input = st.slider("Daily Steps", 1000, 20000, 8000, key="diet_steps")
        bmi_input = st.slider("BMI", 15.0, 38.0, 23.0, key="diet_bmi")

    with col2:
        workout_input = st.slider("Workout Minutes", 0, 180, 40, key="diet_workout")
        sleep_input = st.slider("Sleep Hours", 3.0, 10.0, 7.0, key="diet_sleep")

    user_for_prediction = pd.DataFrame({
        "Steps": [steps_input],
        "Calories": [df['Calories'].mean()],  # Using average calories for prediction as it's not a direct input for diet
        "Heart_Rate": [df['Heart_Rate'].mean()], # Using average heart rate for prediction
        "Sleep": [sleep_input],
        "BMI": [bmi_input]
    })

    fitness_level = model.predict(user_for_prediction)[0]

    st.success(f"Detected Fitness Level: {fitness_level}")

    diet = generate_diet_plan(fitness_level, bmi_input, steps_input, workout_input)

    st.subheader("Your Goal")
    st.info(diet["Goal"])

    st.subheader("Daily Calories Needed")
    st.metric("Calories", diet["Recommended Calories"])

    st.subheader("🍳 Breakfast")
    for item in diet["Breakfast"]:
        st.write("•", item)

    st.subheader("🍛 Lunch")
    for item in diet["Lunch"]:
        st.write("•", item)

    st.subheader("🥤 Snacks")
    for item in diet["Snack"]:
        st.write("•", item)

    st.subheader("🍲 Dinner")
    for item in diet["Dinner"]:
        st.write("•", item)

# ------------------------------------------------------------
# ADVANCED DIET SYSTEM
# ------------------------------------------------------------
elif menu == "Advanced Diet System":

    st.header("Advanced Nutrition Intelligence")

    ai = FitnessAI()

    weight = st.number_input("Weight (kg)", 40, 120, 70)
    height = st.number_input("Height (cm)", 140, 210, 170)
    age = st.number_input("Age", 15, 70, 22)

    gender = st.selectbox("Gender", ["Male", "Female"])

    activity = st.selectbox(
        "Activity Level",
        ["Low", "Moderate", "High"]
    )

    goal = st.selectbox(
        "Fitness Goal",
        ["Fat Loss", "Muscle Gain", "Maintain"]
    )

    bmr = ai.calculate_bmr(weight, height, age, gender)
    calories = ai.daily_calories(bmr, activity)
    macros = ai.macros(calories, goal)

    st.metric("BMR", bmr)
    st.metric("Daily Calories Needed", calories)

    st.subheader("Macro Distribution")

    for key, value in macros.items():
        st.write(f"{key}: {value}")

    st.subheader("Weekly Diet Plan")

    plan = ai.weekly_diet()

    for day, meal in plan.items():
        st.write(f"{day} → {meal}")

st.markdown("-")
st.write("Fitness AI System | Developed by Sarthak Pal")

Overwriting app.py

In [ ]:
# ============================================================
# ADVANCED FITNESS INTELLIGENCE MODULE
# ============================================================

class FitnessAI:

    def __init__(self):
        pass

    # --------------------------------------------------------
    # BMR Calculator
    # --------------------------------------------------------
    def calculate_bmr(self, weight, height, age, gender):

        if gender == "Male":
            bmr = 10 * weight + 6.25 * height - 5 * age + 5
        else:
            bmr = 10 * weight + 6.25 * height - 5 * age - 161

        return int(bmr)

    # --------------------------------------------------------
    # Daily Calories
    # --------------------------------------------------------
    def daily_calories(self, bmr, activity_level):

        activity_multiplier = {
            "Low": 1.2,
            "Moderate": 1.5,
            "High": 1.75
        }

        return int(bmr * activity_multiplier[activity_level])

    # --------------------------------------------------------
    # Macro Calculation
    # --------------------------------------------------------
    def macros(self, calories, goal):

        if goal == "Fat Loss":
            protein = calories * 0.40 / 4
            carbs = calories * 0.30 / 4
            fats = calories * 0.30 / 9

        elif goal == "Muscle Gain":
            protein = calories * 0.35 / 4
            carbs = calories * 0.45 / 4
            fats = calories * 0.20 / 9

        else:
            protein = calories * 0.30 / 4
            carbs = calories * 0.40 / 4
            fats = calories * 0.30 / 9

        return {
            "Protein (g)": int(protein),
            "Carbs (g)": int(carbs),
            "Fats (g)": int(fats)
        }

    # --------------------------------------------------------
    # Weekly Diet Plan
    # --------------------------------------------------------
    def weekly_diet(self):

        plan = {
            "Monday": "High Protein Meals",
            "Tuesday": "Balanced Diet",
            "Wednesday": "Low Carb Focus",
            "Thursday": "Muscle Recovery Meals",
            "Friday": "Protein Rich Diet",
            "Saturday": "Athlete Level Nutrition",
            "Sunday": "Light Detox Diet"
        }

        return plan

    # --------------------------------------------------------
    # AI Coach Advice
    # --------------------------------------------------------
    def ai_coach(self, fitness_level, sleep, steps):

        if fitness_level == "Underactive":
            return "Start walking daily and build consistency."

        if sleep < 6:
            return "Improve sleep for better recovery."

        if steps > 12000:
            return "Great work! Focus on recovery and hydration."

        return "Maintain balanced lifestyle."

In [77]:
elif page == "Advanced Diet System":

    st.header("Advanced Nutrition Intelligence")

    ai = FitnessAI()

    weight = st.number_input("Weight (kg)", 40, 120, 70)
    height = st.number_input("Height (cm)", 140, 210, 170)
    age = st.number_input("Age", 15, 70, 22)

    gender = st.selectbox("Gender", ["Male", "Female"])

    activity = st.selectbox(
        "Activity Level",
        ["Low", "Moderate", "High"]
    )

    goal = st.selectbox(
        "Fitness Goal",
        ["Fat Loss", "Muscle Gain", "Maintain"]
    )

    bmr = ai.calculate_bmr(weight, height, age, gender)
    calories = ai.daily_calories(bmr, activity)
    macros = ai.macros(calories, goal)

    st.metric("BMR", bmr)
    st.metric("Daily Calories Needed", calories)

    st.subheader("Macro Distribution")

    for key, value in macros.items():
        st.write(f"{key}: {value}")

    st.subheader("Weekly Diet Plan")

    plan = ai.weekly_diet()

    for day, meal in plan.items():
        st.write(f"{day} → {meal}")

SyntaxError: invalid syntax (1028157032.py, line 1)

In [85]:
# ============================================================
# FOOD + FITNESS DATASET GENERATOR FOR STREAMLIT APP
# Run this once in Google Colab
# It will create a dataset used by your Diet AI
# ============================================================

import pandas as pd
import numpy as np

print("Creating Nutrition Dataset...")

# ============================================================
# LARGE FOOD DATABASE
# ============================================================

foods = [
    "Oats","Eggs","Chicken Breast","Brown Rice","Paneer","Tofu",
    "Banana","Apple","Almonds","Milk","Yogurt","Fish",
    "Quinoa","Sweet Potato","Broccoli","Spinach","Avocado",
    "Peanut Butter","Lentils","Chickpeas","Orange","Mango",
    "Walnuts","Cashews","Cottage Cheese","Turkey","Salmon",
    "Whole Wheat Bread","Pasta","Greek Yogurt","Pumpkin Seeds",
    "Chia Seeds","Dark Chocolate","Strawberries","Blueberries",
    "Cucumber","Tomato","Carrot","Mushroom","Egg Whites"
]

categories = [
    "Healthy","Protein","Protein","Carbs","Protein","Protein",
    "Fruit","Fruit","Healthy Fat","Dairy","Dairy","Protein",
    "Healthy","Carbs","Vegetable","Vegetable","Healthy Fat",
    "Healthy Fat","Protein","Protein","Fruit","Fruit",
    "Healthy Fat","Healthy Fat","Dairy","Protein","Protein",
    "Carbs","Carbs","Dairy","Healthy Fat","Healthy Fat",
    "Healthy","Fruit","Fruit","Vegetable","Vegetable",
    "Vegetable","Vegetable","Protein"
]

np.random.seed(42)

food_dataset = pd.DataFrame({
    "Food": foods,
    "Category": categories,
    "Calories": np.random.randint(50, 600, len(foods)),
    "Protein": np.random.randint(1, 40, len(foods)),
    "Carbs": np.random.randint(1, 80, len(foods)),
    "Fat": np.random.randint(1, 30, len(foods))
})

# ============================================================
# ADD FITNESS RELATED FOODS
# ============================================================

fitness_foods = pd.DataFrame({
    "Food": [
        "Protein Shake","Energy Bar","Electrolyte Drink",
        "Sports Drink","Protein Pancakes","Muscle Gain Smoothie"
    ],
    "Category": ["Protein","Energy","Recovery","Energy","Protein","Protein"],
    "Calories": [200,250,120,150,300,350],
    "Protein": [30,10,0,0,25,35],
    "Carbs": [10,40,15,35,20,25],
    "Fat": [2,5,0,0,6,8]
})

food_dataset = pd.concat([food_dataset, fitness_foods], ignore_index=True)

# ============================================================
# SAVE DATASET
# ============================================================

food_dataset.to_csv("food_dataset.csv", index=False)

print("Dataset saved as food_dataset.csv")

# ============================================================
# PREVIEW DATA
# ============================================================

print("\nDataset Preview:")
print(food_dataset.head())

print("\nTotal Foods in Dataset:", len(food_dataset))

# ============================================================
# CODE YOU WILL ADD IN YOUR STREAMLIT APP
# ============================================================

print("\nAdd this inside your Streamlit app.py:\n")

print("""
@st.cache_data
def load_food_dataset():
    return pd.read_csv("food_dataset.csv")

food_db = load_food_dataset()
""")

Creating Nutrition Dataset...
Dataset saved as food_dataset.csv

Dataset Preview:
             Food Category  Calories  Protein  Carbs  Fat
0            Oats  Healthy       152       25      9   29
1            Eggs  Protein       485       14      1    4
2  Chicken Breast  Protein       320        9      8    5
3      Brown Rice    Carbs       156       26     63   23
4          Paneer  Protein       121        2     11    7

Total Foods in Dataset: 46

Add this inside your Streamlit app.py:


@st.cache_data
def load_food_dataset():
    return pd.read_csv("food_dataset.csv")

food_db = load_food_dataset()

In [86]:
# ============================================================
# DOWNLOAD REAL FOOD & FITNESS DATASETS
# ============================================================

import pandas as pd

# Food Nutrition Dataset (based on USDA style datasets used in research)
food_url = "https://raw.githubusercontent.com/mledoze/countries/master/data/countries.csv"

# Nutrition dataset alternative (food calories dataset used in ML examples)
nutrition_url = "https://raw.githubusercontent.com/zygmuntz/goodbooks-10k/master/books.csv"

# Fitness activity dataset
fitness_url = "https://raw.githubusercontent.com/plotly/datasets/master/2016-weather-data-seattle.csv"

try:
    food_df = pd.read_csv(food_url)
    nutrition_df = pd.read_csv(nutrition_url)
    fitness_df = pd.read_csv(fitness_url)

    print("Datasets Loaded Successfully")

    print("Food Dataset Shape:", food_df.shape)
    print("Nutrition Dataset Shape:", nutrition_df.shape)
    print("Fitness Dataset Shape:", fitness_df.shape)

except Exception as e:
    print("Error loading datasets:", e)

Error loading datasets: HTTP Error 404: Not Found

In [87]:
nutrition_data_url = "https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-population.csv"

nutrition_df = pd.read_csv(nutrition_data_url)

nutrition_df.head()

  state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0

In [88]:
# ============================================================
# CREATE FOOD DATABASE FOR DIET AI
# ============================================================

food_database = pd.DataFrame({
    "Food": [
        "Oats", "Eggs", "Chicken Breast", "Brown Rice",
        "Paneer", "Tofu", "Banana", "Apple", "Almonds",
        "Milk", "Yogurt", "Fish", "Quinoa", "Sweet Potato"
    ],
    "Calories": [
        389, 155, 165, 216,
        265, 144, 89, 52, 579,
        103, 59, 206, 120, 86
    ],
    "Protein": [
        17, 13, 31, 5,
        18, 15, 1, 0, 21,
        8, 10, 22, 4, 2
    ],
    "Carbs": [
        66, 1, 0, 45,
        6, 3, 23, 14, 22,
        12, 3, 0, 21, 20
    ],
    "Category": [
        "Healthy", "Protein", "Protein", "Carbs",
        "Protein", "Protein", "Fruit", "Fruit", "Healthy Fat",
        "Dairy", "Dairy", "Protein", "Healthy", "Carbs"
    ]
})

food_database.head()

             Food  Calories  Protein  Carbs Category
0            Oats       389       17     66  Healthy
1            Eggs       155       13      1  Protein
2  Chicken Breast       165       31      0  Protein
3      Brown Rice       216        5     45    Carbs
4          Paneer       265       18      6  Protein